import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';
import 'package:flutter_datetime_picker/flutter_datetime_picker.dart';
import 'package:provider/provider.dart';
import '../../auth/firebase_auth_methods.dart';
import '../../utils/action_button.dart';
import '../../utils/expandable_fab.dart';
import 'package:dropdown_search/dropdown_search.dart';

import '../../utils/showSnackBar.dart';

class ProfilePage3 extends StatefulWidget {
  const ProfilePage3({super.key});

  @override
  State<ProfilePage3> createState() => _RegisterPageState();
}

class _RegisterPageState extends State<ProfilePage3> {
  FirebaseFirestore firestore = FirebaseFirestore.instance;
  final uid = FirebaseAuth.instance.currentUser!.uid;
  final email = FirebaseAuth.instance.currentUser!.email;
  final creatinTime = FirebaseAuth.instance.currentUser!.metadata.creationTime;

  final TextEditingController firstNameController = TextEditingController();
  final TextEditingController middleNameController = TextEditingController();
  final TextEditingController surNameController = TextEditingController();
  final TextEditingController sexController = TextEditingController();
  final TextEditingController birthController = TextEditingController();
  final TextEditingController contactNumController = TextEditingController();
  final TextEditingController addressController = TextEditingController();
  final TextEditingController postalCodeController = TextEditingController();
  final TextEditingController barangayController = TextEditingController();

  CollectionReference users = FirebaseFirestore.instance.collection('users');
  // FormState form = _formKey.currentState;
  // form.save();
  final DocumentReference dbRef = FirebaseFirestore.instance
      .collection("users")
      .doc('17CS1tjH7AT0p2uPznyDWtaeaY43');

  // late DatabaseReference dbRef;
  // dbRef = FirebaseFirestore.instance.collection('users').doc('');

  String? uuid = "";
  var selectedSex;
  var selectedRegion;
  var selectedProvince;
  var selectedCity;
  var agencyType;
  String firstName = "";
  String middleName = "";
  String sureName = "";
  String sex = "";
  String contactNum = "";
  String address = "";
  String bday = "";
  String zipcode = "";
  String region = "";
  String province = "";
  String municipality = "";

  // Future<void> getUsers() async {
  //   FirebaseAuth.instance.authStateChanges().listen((User? user) {
  //     if (user == null) {
  //       showSnackBar(context, 'User is currently signed out!');
  //     } else {
  //       uuid = user.uid;
  //       //https://www.youtube.com/watch?v=ErP_xomHKTw&t=394s
  //       FirebaseFirestore.instance //might be used for task1
  //           .collection('users')
  //           .get()
  //           .then((QuerySnapshot querySnapshot) {
  //         querySnapshot.docs.forEach((doc) {
  //           firstName = doc['first'];
  //           middleName = doc['middle'];
  //           sureName = doc['surname'];
  //           sex = doc['sex'];
  //           contactNum = doc['contactNum'];
  //           address = doc['address'];
  //           bday = doc['bday'];
  //           zipcode = doc['zipcode'];
  //           region = doc['region'];
  //           province = doc['province'];
  //           municipality = doc['municipality'];
  //           agencyType = doc['agencyType'];
  //         });
  //       });
  //     }
  //   });
  // }

  // Future<void> addUser() {
  //   FirebaseAuth.instance.authStateChanges().listen((User? user) {
  //     if (user == null) {
  //       showSnackBar(context, 'User is currently signed out!');
  //     } else {
  //       uuid = user.uid;
  //     }
  //   });

  //   var createdTime = creatinTime.toString();
  //   String creationTime = createdTime.substring(0, createdTime.indexOf('.'));
  //   DateTime _now = DateTime.now();

  //   return users.doc(uuid).set({
  //     'uuid': uuid,
  //     'first': firstNameController.text,
  //     'middle': middleNameController.text,
  //     'surname': surNameController.text,
  //     'sex': selectedSex,
  //     'bday': birthController.text,
  //     'address': addressController.text,
  //     'barangay': barangayController.text,
  //     'contactNum': contactNumController.text,
  //     'region': selectedRegion,
  //     'province': selectedProvince,
  //     'city': selectedCity,
  //     'agency': agencyType,
  //     'createdTime': creationTime,
  //     'updatedTime': _now,
  //   });
  //   // .then();
  //   // .catchError((error) => print("Failed to add user: $error"));
  //   // .then((value) => print("User Added"))
  //   // .catchError((error) => print("Failed to add user: $error"));
  // }

//   // age/sex/e.contact-Relationship-contactnum/pre-existing conditions/marital status
//   //Family Doctor Name-e.contact/Taking any medications, currently? Yes/No, If yes, please list it here
//   //Pre-existing conditions: Pregnancy//Congestive Heart Failure/Hypertension/Epilepsy
//   //A pre-existing condition is a health problem you had before the date that your new health coverage starts.
//   //Epilepsy, cancer, diabetes, lupus, sleep apnea, and pregnancy are all examples of pre-existing conditions.

  // @override
  // void initState() {
  //   super.initState();
  //   // getUsers();
  // }
  late StreamSubscription _subscription;

  final DocumentReference profile = FirebaseFirestore.instance
      .collection("users")
      .doc('17CS1tjH7AT0p2uPznyDWtaeaY43');

  final _ref = FirebaseDatabase.instance
      .ref('tasks')
      .child('-NCnoDCrLgSeOWt213eZ')
      .child('agencyType');

  @override
  void initState() {
    super.initState();
    // _subscription = _ref.onValue.listen((data) {
    //   String value = data.snapshot.value as String;
    //   updateOnChanged(value);
    // });
  }

  updateOnChanged(String value) async {
    setState(() {
      firstNameController.value = firstNameController.value.copyWith(
        text: value,
      );
    });
  }

  // Stream<List<UserModel>> getUserList() {
  //   return profile.collection('user').snapshots().map((snapShot) => snapShot
  //       .documents
  //       .map((document) => UserModel.fromJson(document.data))
  //       .toList());
  // }

  // void addUser() {
  //   var addUserData = Map<String, dynamic>();
  //   addUserData['name'] = "Andrew Holder";
  //   addUserData['age'] = "31yrs";
  //   return _fireStoreDataBase
  //       .collection('user')
  //       .document('user_03')
  //       .setData(addUserData);
  // }

  @override
  void dispose() {
    firstNameController.dispose();
    middleNameController.dispose();
    surNameController.dispose();
    sexController.dispose();
    contactNumController.dispose();
    addressController.dispose();
    postalCodeController.dispose();
    birthController.dispose();
    barangayController.dispose();
    super.dispose();
  }

  final List<String> regionList = [
    "Region I",
    "Region II",
    "Region III",
    "Region IV-A",
    "MIMAROPA Region",
    "Region V",
    "Region VI",
    "Region VII",
    "Region VIII",
    "Region IX",
    "Region X",
    "Region XI",
    "Region XII",
    "National Capital Region",
    "Cordillera Administrative Region",
    "Region XIII",
    "Bangsamoro Autonomous Region in Muslim Mindanao"
  ];

  final List<String> sexList = [
    "Male",
    "Female",
  ];

  // void updateProfile() {
  //   var createdTime = creatinTime.toString();
  //   String result = createdTime.substring(0, createdTime.indexOf('.'));
  //   print(uid);
  // }

  @override
  Widget build(BuildContext context) => WillPopScope(
        onWillPop: () async {
          return true;
        },
        child: Scaffold(
          backgroundColor: Colors.grey[300],
          body: SafeArea(
            child: SingleChildScrollView(
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Container(
                      width: 130,
                      height: 130,
                      decoration: BoxDecoration(
                        border: Border.all(
                            width: 4,
                            color: Theme.of(context).scaffoldBackgroundColor),
                        boxShadow: [
                          BoxShadow(
                              spreadRadius: 2,
                              blurRadius: 10,
                              color: Colors.black.withOpacity(0.1),
                              offset: Offset(0, 10))
                        ],
                        shape: BoxShape.circle,
                        image: DecorationImage(
                          fit: BoxFit.cover,
                          image: Image.asset(
                            'assets/images/AA-logo.png',
                          ).image,
                        ),
                      ),
                    ),
                    const SizedBox(height: 10),
//===============================First==========================================
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          border: Border.all(color: Colors.white),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.only(left: 20.0),
                          child: TextFormField(
                            controller: firstNameController,
                            decoration: const InputDecoration(
                              border: InputBorder.none,
                              hintText: 'First Name:*',
                            ),
                          ),
                        ),
                      ),
                    ),
//===============================Middle=========================================
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          border: Border.all(color: Colors.white),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.only(left: 20.0),
                          child: TextField(
                            controller: middleNameController,
                            decoration: const InputDecoration(
                              border: InputBorder.none,
                              hintText: 'Middle Name:*',
                            ),
                          ),
                        ),
                      ),
                    ),
//===============================Surname========================================
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          border: Border.all(color: Colors.white),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.only(left: 20.0),
                          child: TextField(
                            controller: surNameController,
                            decoration: const InputDecoration(
                              border: InputBorder.none,
                              hintText: 'Surname:*',
                            ),
                          ),
                        ),
                      ),
                    ),
//===============================Sex-BDay=======================================
                    const SizedBox(height: 10),
                    Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 35.0),
                        child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                            children: <Widget>[
                              Align(
                                  alignment:
                                      const AlignmentDirectional(-0.75, 0),
                                  child: DropdownButton(
                                    value: selectedSex,
                                    isExpanded: false,
                                    hint: const Text(
                                      "Sex",
                                    ),
                                    icon: const Icon(Icons.arrow_downward),
                                    elevation: 10,
                                    items: sexList
                                        .map(
                                            (dynamic value) => DropdownMenuItem(
                                                  value: value,
                                                  child: Text(
                                                    value,
                                                    style: const TextStyle(
                                                        fontWeight:
                                                            FontWeight.bold),
                                                  ),
                                                ))
                                        .toList(),
                                    onChanged: (newmenu) {
                                      setState(() {
                                        selectedSex = newmenu;
                                      });
                                    },
                                  )),
                              const SizedBox(width: 20),
                              IconButton(
                                icon: const Icon(Icons.date_range, size: 40.0),
                                onPressed: () {
                                  DatePicker.showDatePicker(context,
                                      showTitleActions: true,
                                      minTime: DateTime(1940, 1, 1),
                                      maxTime: DateTime(2012, 12, 31),
                                      theme: const DatePickerTheme(
                                          headerColor: Colors.green,
                                          backgroundColor: Colors.blue,
                                          itemStyle: TextStyle(
                                              color: Colors.white,
                                              fontWeight: FontWeight.bold,
                                              fontSize: 18),
                                          doneStyle: TextStyle(
                                              color: Colors.white,
                                              fontSize: 16)),
                                      onConfirm: (date) {
                                    birthController.text = date
                                        .toString()
                                        .replaceAll('00:00:00.000', '');
                                  },
                                      currentTime: DateTime.now(),
                                      locale: LocaleType.en);
                                },
                              ),
                              const SizedBox(width: 20),
                              Expanded(
                                child: Container(
                                  decoration: BoxDecoration(
                                    color: Colors.grey[400],
                                    border: Border.all(color: Colors.white),
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                  child: Padding(
                                    padding: const EdgeInsets.only(left: 10.0),
                                    child: TextField(
                                      readOnly: true,
                                      enableInteractiveSelection: false,
                                      controller: birthController,
                                      decoration: const InputDecoration(
                                        border: InputBorder.none,
                                        hintText: 'Birth Date:',
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ])),
//===============================Address========================================
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          border: Border.all(color: Colors.white),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.only(left: 20.0),
                          child: TextField(
                            controller: addressController,
                            decoration: const InputDecoration(
                              border: InputBorder.none,
                              hintText:
                                  '*Address: House #, Street, Subdivision',
                            ),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 10),
                    Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 25.0),
                        child: Container(
                            decoration: BoxDecoration(
                              color: Colors.grey[200],
                              border: Border.all(color: Colors.white),
                              borderRadius: BorderRadius.circular(12),
                            ),
                            child: Padding(
                              padding: const EdgeInsets.only(left: 20.0),
                              child: TextField(
                                  controller: barangayController,
                                  decoration: const InputDecoration(
                                    border: InputBorder.none,
                                    hintText: 'Barangay:*',
                                  )),
                            ))),
//============================Contact-ZipCode===================================
                    const SizedBox(height: 10),
                    Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 25.0),
                        child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                            children: [
                              Expanded(
                                  child: Container(
                                      decoration: BoxDecoration(
                                        color: Colors.grey[200],
                                        border: Border.all(color: Colors.white),
                                        borderRadius: BorderRadius.circular(12),
                                      ),
                                      child: Padding(
                                          padding:
                                              const EdgeInsets.only(left: 20.0),
                                          child: TextField(
                                              controller: contactNumController,
                                              decoration: const InputDecoration(
                                                border: InputBorder.none,
                                                hintText: 'Contact #:*',
                                              ))))),
                              const SizedBox(width: 10),
                              Expanded(
                                  child: Container(
                                decoration: BoxDecoration(
                                  color: Colors.grey[200],
                                  border: Border.all(color: Colors.white),
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                child: Padding(
                                    padding: const EdgeInsets.only(left: 20.0),
                                    child: TextField(
                                        controller: postalCodeController,
                                        decoration: const InputDecoration(
                                          border: InputBorder.none,
                                          hintText: 'Zip Coder:*',
                                        ))),
                              ))
                            ])),
//==================================Region======================================
                    const SizedBox(height: 10),
                    Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 25.0),
                        child: DropdownSearch<String>(
                          mode: Mode.MENU,
                          showSelectedItems: true,
                          items: regionList,
                          showSearchBox: true,
                          searchFieldProps: const TextFieldProps(
                            cursorColor: Colors.blue,
                          ),
                          dropdownSearchDecoration: const InputDecoration(
                            labelText: "Select your Region*",
                            hintText: "Search Region here...",
                          ),
                          onChanged: (newmenu) {
                            setState(() {
                              selectedRegion = newmenu.toString();
                            });
                          },
                        )),
//===================================Province===================================
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: DropdownSearch<String>(
                        mode: Mode.MENU,
                        showSelectedItems: true,
                        items: const [
                          "Ilocos Norte",
                          "Ilocos Sur",
                          "La Union",
                          "Pangasinan",
                          "Batanes",
                          "Cagayan",
                          "Isabela",
                          "Nueva Vizcaya",
                          "Quirino",
                          "Bataan",
                          "Bulacan",
                          "Nueva Ecija",
                          "Pampanga",
                          "Tarlac",
                          "Zambales",
                          "Aurora",
                          "Batangas",
                          "Cavite",
                          "Laguna",
                          "Quezon",
                          "Rizal",
                          "Marinduque",
                          "Occidental Mindoro",
                          "Oriental Mindoro",
                          "Palawan",
                          "Romblon",
                          "Albay",
                          "Camarines Norte",
                          "Camarines Sur",
                          "Catanduanes",
                          "Masbate",
                          "Sorsogon",
                          "Aklan",
                          "Antique",
                          "Capiz",
                          "Iloilo",
                          "Negros Occidental",
                          "Guimaras",
                          "Bohol",
                          "Cebu",
                          "Negros Oriental",
                          "Siquijor",
                          "Eastern Samar",
                          "Leyte",
                          "Northern Samar",
                          "Samar",
                          "Southern Leyte",
                          "Biliran",
                          "Zamboanga Del Norte",
                          "Zamboanga Del Sur",
                          "Zamboanga Sibugay",
                          "Bukidnon",
                          "Camiguin",
                          "Lanao Del Norte",
                          "Misamis Occidental",
                          "Misamis Oriental",
                          "Davao Del Norte",
                          "Davao Del Sur",
                          "Davao Oriental",
                          "Davao De Oro",
                          "Davao Occidental",
                          "Cotabato",
                          "South Cotabato",
                          "Sultan Kudarat",
                          "Sarangani",
                          "Abra",
                          "Benguet",
                          "Ifugao",
                          "Kalinga",
                          "Mountain Province",
                          "Apayao",
                          "Agusan Del Norte",
                          "Agusan Del Sur",
                          "Surigao Del Norte",
                          "Surigao Del Sur",
                          "Dinagat Islands",
                          "Basilan",
                          "Lanao Del Sur",
                          "Maguindanao",
                          "Sulu",
                          "Tawi-Tawi"
                        ],
                        dropdownSearchDecoration: const InputDecoration(
                          labelText: "Select your Province*",
                          // hintText: "country in menu mode",
                        ),
                        onChanged: (newmenu) {
                          setState(() {
                            selectedProvince = newmenu.toString();
                          });
                        },
                        showSearchBox: true,
                        searchFieldProps: const TextFieldProps(
                          cursorColor: Colors.blue,
                        ),
                      ),
                    ),
//===============================Municipality===================================
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: DropdownSearch<String>(
                        mode: Mode.MENU,
                        showSelectedItems: true,
                        items: const [
                          "Adams",
                          "Bacarra",
                          "Badoc",
                          "Bangui",
                          "Burgos",
                          "Carasi",
                          "Currimao",
                          "Dingras",
                          "Dumalneg",
                          "Banna",
                          "Marcos",
                          "Nueva Era",
                          "Pagudpud",
                          "Paoay",
                          "Pasuquin",
                          "Piddig",
                          "Pinili",
                          "San Nicolas",
                          "Sarrat",
                          "Solsona",
                          "Vintar",
                          "Alilem",
                          "Banayoyo",
                          "Bantay",
                          "Burgos",
                          "Cabugao",
                          "Caoayan",
                          "Cervantes",
                          "Galimuyod",
                          "Gregorio Del Pilar",
                          "Lidlidda",
                          "Magsingal",
                          "Nagbukel",
                          "Narvacan",
                          "Quirino",
                          "Salcedo",
                          "San Emilio",
                          "San Esteban",
                          "San Ildefonso",
                          "San Juan",
                          "San Vicente",
                          "Santa",
                          "Santa Catalina",
                          "Santa Cruz",
                          "Santa Lucia",
                          "Santa Maria",
                          "Santiago",
                          "Santo Domingo",
                          "Sigay",
                          "Sinait",
                          "Sugpon",
                          "Suyo",
                          "Tagudin",
                          "Agoo",
                          "Aringay",
                          "Bacnotan",
                          "Bagulin",
                          "Balaoan",
                          "Bangar",
                          "Bauang",
                          "Burgos",
                          "Caba",
                          "Luna",
                          "Naguilian",
                          "Pugo",
                          "Rosario",
                          "San Gabriel",
                          "San Juan",
                          "Santo Tomas",
                          "Santol",
                          "Sudipen",
                          "Tubao",
                          "Agno",
                          "Aguilar",
                          "Alcala",
                          "Anda",
                          "Asingan",
                          "Balungao",
                          "Bani",
                          "Basista",
                          "Bautista",
                          "Bayambang",
                          "Binalonan",
                          "Binmaley",
                          "Bolinao",
                          "Bugallon",
                          "Burgos",
                          "Calasiao",
                          "Dasol",
                          "Infanta",
                          "Labrador",
                          "Lingayen",
                          "Mabini",
                          "Malasiqui",
                          "Manaoag",
                          "Mangaldan",
                          "Mangatarem",
                          "Mapandan",
                          "Natividad",
                          "Pozorrubio",
                          "Rosales",
                          "San Fabian",
                          "San Jacinto",
                          "San Manuel",
                          "San Nicolas",
                          "San Quintin",
                          "Santa Barbara",
                          "Santa Maria",
                          "Santo Tomas",
                          "Sison",
                          "Sual",
                          "Tayug",
                          "Umingan",
                          "Urbiztondo",
                          "Villasis",
                          "Laoac",
                          "Basco",
                          "Itbayat",
                          "Ivana",
                          "Mahatao",
                          "Sabtang",
                          "Uyugan",
                          "Abulug",
                          "Alcala",
                          "Allacapan",
                          "Amulung",
                          "Aparri",
                          "Baggao",
                          "Ballesteros",
                          "Buguey",
                          "Calayan",
                          "Camalaniugan",
                          "Claveria",
                          "Enrile",
                          "Gattaran",
                          "Gonzaga",
                          "Iguig",
                          "Lal-Lo",
                          "Lasam",
                          "Pamplona",
                          "PeÃ±ablanca",
                          "Piat",
                          "Rizal",
                          "Sanchez-Mira",
                          "Santa Ana",
                          "Santa Praxedes",
                          "Santa Teresita",
                          "Santo NiÃ±o",
                          "Solana",
                          "Tuao",
                          "Alicia",
                          "Angadanan",
                          "Aurora",
                          "Benito Soliven",
                          "Burgos",
                          "Cabagan",
                          "Cabatuan",
                          "Cordon",
                          "Dinapigue",
                          "Divilacan",
                          "Echague",
                          "Gamu",
                          "Jones",
                          "Luna",
                          "Maconacon",
                          "Delfin Albano",
                          "Mallig",
                          "Naguilian",
                          "Palanan",
                          "Quezon",
                          "Quirino",
                          "Ramon",
                          "Reina Mercedes",
                          "Roxas",
                          "San Agustin",
                          "San Guillermo",
                          "San Isidro",
                          "San Manuel",
                          "San Mariano",
                          "San Mateo",
                          "San Pablo",
                          "Santa Maria",
                          "Santo Tomas",
                          "Tumauini",
                          "Ambaguio",
                          "Aritao",
                          "Bagabag",
                          "Bambang",
                          "Bayombong",
                          "Diadi",
                          "Dupax Del Norte",
                          "Dupax Del Sur",
                          "Kasibu",
                          "Kayapa",
                          "Quezon",
                          "Santa Fe",
                          "Solano",
                          "Villaverde",
                          "Alfonso Castaneda",
                          "Aglipay",
                          "Cabarroguis",
                          "Diffun",
                          "Maddela",
                          "Saguday",
                          "Nagtipunan",
                          "Abucay",
                          "Bagac",
                          "Dinalupihan",
                          "Hermosa",
                          "Limay",
                          "Mariveles",
                          "Morong",
                          "Orani",
                          "Orion",
                          "Pilar",
                          "Samal",
                          "Angat",
                          "Balagtas",
                          "Baliuag",
                          "Bocaue",
                          "Bulacan",
                          "Bustos",
                          "Calumpit",
                          "Guiguinto",
                          "Hagonoy",
                          "Marilao",
                          "Norzagaray",
                          "Obando",
                          "Pandi",
                          "Paombong",
                          "Plaridel",
                          "Pulilan",
                          "San Ildefonso",
                          "San Miguel",
                          "San Rafael",
                          "Santa Maria",
                          "DoÃ±a Remedios Trinidad",
                          "Aliaga",
                          "Bongabon",
                          "Cabiao",
                          "Carranglan",
                          "Cuyapo",
                          "Gabaldon",
                          "General Mamerto Natividad",
                          "General Tinio",
                          "Guimba",
                          "Jaen",
                          "Laur",
                          "Licab",
                          "Llanera",
                          "Lupao",
                          "Nampicuan",
                          "Pantabangan",
                          "PeÃ±aranda",
                          "Quezon",
                          "Rizal",
                          "San Antonio",
                          "San Isidro",
                          "San Leonardo",
                          "Santa Rosa",
                          "Santo Domingo",
                          "Talavera",
                          "Talugtug",
                          "Zaragoza",
                          "Apalit",
                          "Arayat",
                          "Bacolor",
                          "Candaba",
                          "Floridablanca",
                          "Guagua",
                          "Lubao",
                          "Macabebe",
                          "Magalang",
                          "Masantol",
                          "Mexico",
                          "Minalin",
                          "Porac",
                          "San Luis",
                          "San Simon",
                          "Santa Ana",
                          "Santa Rita",
                          "Sto. Tomas",
                          "Sasmuan",
                          "Anao",
                          "Bamban",
                          "Camiling",
                          "Capas",
                          "Concepcion",
                          "Gerona",
                          "La Paz",
                          "Mayantoc",
                          "Moncada",
                          "Paniqui",
                          "Pura",
                          "Ramos",
                          "San Clemente",
                          "San Manuel",
                          "Santa Ignacia",
                          "Victoria",
                          "San Jose",
                          "Botolan",
                          "Cabangan",
                          "Candelaria",
                          "Castillejos",
                          "Iba",
                          "Masinloc",
                          "Palauig",
                          "San Antonio",
                          "San Felipe",
                          "San Marcelino",
                          "San Narciso",
                          "Santa Cruz",
                          "Subic",
                          "Baler",
                          "Casiguran",
                          "Dilasag",
                          "Dinalungan",
                          "Dingalan",
                          "Dipaculao",
                          "Maria Aurora",
                          "San Luis",
                          "Agoncillo",
                          "Alitagtag",
                          "Balayan",
                          "Balete",
                          "Bauan",
                          "Calaca",
                          "Calatagan",
                          "Cuenca",
                          "Ibaan",
                          "Laurel",
                          "Lemery",
                          "Lian",
                          "Lobo",
                          "Mabini",
                          "Malvar",
                          "Mataasnakahoy",
                          "Nasugbu",
                          "Padre Garcia",
                          "Rosario",
                          "San Jose",
                          "San Juan",
                          "San Luis",
                          "San Nicolas",
                          "San Pascual",
                          "Santa Teresita",
                          "Taal",
                          "Talisay",
                          "Taysan",
                          "Tingloy",
                          "Tuy",
                          "Alfonso",
                          "Amadeo",
                          "Carmona",
                          "General Emilio Aguinaldo",
                          "Indang",
                          "Kawit",
                          "Magallanes",
                          "Maragondon",
                          "Mendez",
                          "Naic",
                          "Noveleta",
                          "Rosario",
                          "Silang",
                          "Tanza",
                          "Ternate",
                          "Gen. Mariano Alvarez",
                          "Alaminos",
                          "Bay",
                          "Calauan",
                          "Cavinti",
                          "Famy",
                          "Kalayaan",
                          "Liliw",
                          "Los Baños",
                          "Luisiana",
                          "Lumban",
                          "Mabitac",
                          "Magdalena",
                          "Majayjay",
                          "Nagcarlan",
                          "Paete",
                          "Pagsanjan",
                          "Pakil",
                          "Pangil",
                          "Pila",
                          "Rizal",
                          "Santa Cruz",
                          "Santa Maria",
                          "Siniloan",
                          "Victoria",
                          "Agdangan",
                          "Alabat",
                          "Atimonan",
                          "Buenavista",
                          "Burdeos",
                          "Calauag",
                          "Candelaria",
                          "Catanauan",
                          "Dolores",
                          "General Luna",
                          "General Nakar",
                          "Guinayangan",
                          "Gumaca",
                          "Infanta",
                          "Jomalig",
                          "Lopez",
                          "Lucban",
                          "Macalelon",
                          "Mauban",
                          "Mulanay",
                          "Padre Burgos",
                          "Pagbilao",
                          "Panukulan",
                          "Patnanungan",
                          "Perez",
                          "Pitogo",
                          "Plaridel",
                          "Polillo",
                          "Quezon",
                          "Real",
                          "Sampaloc",
                          "San Andres",
                          "San Antonio",
                          "San Francisco",
                          "San Narciso",
                          "Sariaya",
                          "Tagkawayan",
                          "Tiaong",
                          "Unisan",
                          "Angono",
                          "Baras",
                          "Binangonan",
                          "Cainta",
                          "Cardona",
                          "Jala-Jala",
                          "Rodriguez",
                          "Morong",
                          "Pililla",
                          "San Mateo",
                          "Tanay",
                          "Taytay",
                          "Teresa",
                          "Boac",
                          "Buenavista",
                          "Gasan",
                          "Mogpog",
                          "Santa Cruz",
                          "Torrijos",
                          "Abra De Ilog",
                          "Calintaan",
                          "Looc",
                          "Lubang",
                          "Magsaysay",
                          "Mamburao",
                          "Paluan",
                          "Rizal",
                          "Sablayan",
                          "San Jose",
                          "Santa Cruz",
                          "Baco",
                          "Bansud",
                          "Bongabong",
                          "Bulalacao",
                          "Gloria",
                          "Mansalay",
                          "Naujan",
                          "Pinamalayan",
                          "Pola",
                          "Puerto Galera",
                          "Roxas",
                          "San Teodoro",
                          "Socorro",
                          "Victoria",
                          "Aborlan",
                          "Agutaya",
                          "Araceli",
                          "Balabac",
                          "Bataraza",
                          "Brooke's Point",
                          "Busuanga",
                          "Cagayancillo",
                          "Coron",
                          "Cuyo",
                          "Dumaran",
                          "El Nido",
                          "Linapacan",
                          "Magsaysay",
                          "Narra",
                          "Quezon",
                          "Roxas",
                          "San Vicente",
                          "Taytay",
                          "Kalayaan",
                          "Culion",
                          "Rizal",
                          "Sofronio EspaÃ±ola",
                          "Alcantara",
                          "Banton",
                          "Cajidiocan",
                          "Calatrava",
                          "Concepcion",
                          "Corcuera",
                          "Looc",
                          "Magdiwang",
                          "Odiongan",
                          "Romblon",
                          "San Agustin",
                          "San Andres",
                          "San Fernando",
                          "San Jose",
                          "Santa Fe",
                          "Ferrol",
                          "Santa Maria",
                          "Bacacay",
                          "Camalig",
                          "Daraga",
                          "Guinobatan",
                          "Jovellar",
                          "Libon",
                          "Malilipot",
                          "Malinao",
                          "Manito",
                          "Oas",
                          "Pio Duran",
                          "Polangui",
                          "Rapu-Rapu",
                          "Santo Domingo",
                          "Tiwi",
                          "Basud",
                          "Capalonga",
                          "Daet",
                          "San Lorenzo Ruiz",
                          "Jose Panganiban",
                          "Labo",
                          "Mercedes",
                          "Paracale",
                          "San Vicente",
                          "Santa Elena",
                          "Talisay",
                          "Vinzons",
                          "Baao",
                          "Balatan",
                          "Bato",
                          "Bombon",
                          "Buhi",
                          "Bula",
                          "Cabusao",
                          "Calabanga",
                          "Camaligan",
                          "Canaman",
                          "Caramoan",
                          "Del Gallego",
                          "Gainza",
                          "Garchitorena",
                          "Goa",
                          "Lagonoy",
                          "Libmanan",
                          "Lupi",
                          "Magarao",
                          "Milaor",
                          "Minalabac",
                          "Nabua",
                          "Ocampo",
                          "Pamplona",
                          "Pasacao",
                          "Pili",
                          "Presentacion",
                          "Ragay",
                          "SagÃ±ay",
                          "San Fernando",
                          "San Jose",
                          "Sipocot",
                          "Siruma",
                          "Tigaon",
                          "Tinambac",
                          "Bagamanoc",
                          "Baras",
                          "Bato",
                          "Caramoran",
                          "Gigmoto",
                          "Pandan",
                          "Panganiban",
                          "San Andres",
                          "San Miguel",
                          "Viga",
                          "Virac",
                          "Aroroy",
                          "Baleno",
                          "Balud",
                          "Batuan",
                          "Cataingan",
                          "Cawayan",
                          "Claveria",
                          "Dimasalang",
                          "Esperanza",
                          "Mandaon",
                          "Milagros",
                          "Mobo",
                          "Monreal",
                          "Palanas",
                          "Pio v. Corpuz",
                          "Placer",
                          "San Fernando",
                          "San Jacinto",
                          "San Pascual",
                          "Uson",
                          "Barcelona",
                          "Bulan",
                          "Bulusan",
                          "Casiguran",
                          "Castilla",
                          "Donsol",
                          "Gubat",
                          "Irosin",
                          "Juban",
                          "Magallanes",
                          "Matnog",
                          "Pilar",
                          "Prieto Diaz",
                          "Santa Magdalena",
                          "Altavas",
                          "Balete",
                          "Banga",
                          "Batan",
                          "Buruanga",
                          "Ibajay",
                          "Kalibo",
                          "Lezo",
                          "Libacao",
                          "Madalag",
                          "Makato",
                          "Malay",
                          "Malinao",
                          "Nabas",
                          "New Washington",
                          "Numancia",
                          "Tangalan",
                          "Anini-Y",
                          "Barbaza",
                          "Belison",
                          "Bugasong",
                          "Caluya",
                          "Culasi",
                          "Tobias Fornier",
                          "Hamtic",
                          "Laua-An",
                          "Libertad",
                          "Pandan",
                          "Patnongon",
                          "San Jose",
                          "San Remigio",
                          "Sebaste",
                          "Sibalom",
                          "Tibiao",
                          "Valderrama",
                          "Cuartero",
                          "Dao",
                          "Dumalag",
                          "Dumarao",
                          "Ivisan",
                          "Jamindan",
                          "Ma-Ayon",
                          "Mambusao",
                          "Panay",
                          "Panitan",
                          "Pilar",
                          "Pontevedra",
                          "President Roxas",
                          "Sapi-An",
                          "Sigma",
                          "Tapaz",
                          "Ajuy",
                          "Alimodian",
                          "Anilao",
                          "Badiangan",
                          "Balasan",
                          "Banate",
                          "Barotac Nuevo",
                          "Barotac Viejo",
                          "Batad",
                          "Bingawan",
                          "Cabatuan",
                          "Calinog",
                          "Carles",
                          "Concepcion",
                          "Dingle",
                          "DueÃ±as",
                          "Dumangas",
                          "Estancia",
                          "Guimbal",
                          "Igbaras",
                          "Janiuay",
                          "Lambunao",
                          "Leganes",
                          "Lemery",
                          "Leon",
                          "Maasin",
                          "Miagao",
                          "Mina",
                          "New Lucena",
                          "Oton",
                          "Pavia",
                          "Pototan",
                          "San Dionisio",
                          "San Enrique",
                          "San Joaquin",
                          "San Miguel",
                          "San Rafael",
                          "Santa Barbara",
                          "Sara",
                          "Tigbauan",
                          "Tubungan",
                          "Zarraga",
                          "Binalbagan",
                          "Calatrava",
                          "Candoni",
                          "Cauayan",
                          "Enrique B. Magalona",
                          "Hinigaran",
                          "Hinoba-An",
                          "Ilog",
                          "Isabela",
                          "La Castellana",
                          "Manapla",
                          "Moises Padilla",
                          "Murcia",
                          "Pontevedra",
                          "Pulupandan",
                          "San Enrique",
                          "Toboso",
                          "Valladolid",
                          "Salvador Benedicto",
                          "Buenavista",
                          "Jordan",
                          "Nueva Valencia",
                          "San Lorenzo",
                          "Sibunag",
                          "Alburquerque",
                          "Alicia",
                          "Anda",
                          "Antequera",
                          "Baclayon",
                          "Balilihan",
                          "Batuan",
                          "Bilar",
                          "Buenavista",
                          "Calape",
                          "Candijay",
                          "Carmen",
                          "Catigbian",
                          "Clarin",
                          "Corella",
                          "Cortes",
                          "Dagohoy",
                          "Danao",
                          "Dauis",
                          "Dimiao",
                          "Duero",
                          "Garcia Hernandez",
                          "Guindulman",
                          "Inabanga",
                          "Jagna",
                          "Getafe",
                          "Lila",
                          "Loay",
                          "Loboc",
                          "Loon",
                          "Mabini",
                          "Maribojoc",
                          "Panglao",
                          "Pilar",
                          "President Carlos P. Garcia",
                          "Sagbayan",
                          "San Isidro",
                          "San Miguel",
                          "Sevilla",
                          "Sierra Bullones",
                          "Sikatuna",
                          "Talibon",
                          "Trinidad",
                          "Tubigon",
                          "Ubay",
                          "Valencia",
                          "Bien Unido",
                          "Alcantara",
                          "Alcoy",
                          "Alegria",
                          "Aloguinsan",
                          "Argao",
                          "Asturias",
                          "Badian",
                          "Balamban",
                          "Bantayan",
                          "Barili",
                          "Boljoon",
                          "Borbon",
                          "Carmen",
                          "Catmon",
                          "Compostela",
                          "Consolacion",
                          "Cordova",
                          "Daanbantayan",
                          "Dalaguete",
                          "Dumanjug",
                          "Ginatilan",
                          "Liloan",
                          "Madridejos",
                          "Malabuyoc",
                          "Medellin",
                          "Minglanilla",
                          "Moalboal",
                          "Oslob",
                          "Pilar",
                          "Pinamungajan",
                          "Poro",
                          "Ronda",
                          "Samboan",
                          "San Fernando",
                          "San Francisco",
                          "San Remigio",
                          "Santa Fe",
                          "Santander",
                          "Sibonga",
                          "Sogod",
                          "Tabogon",
                          "Tabuelan",
                          "Tuburan",
                          "Tudela",
                          "Amlan",
                          "Ayungon",
                          "Bacong",
                          "Basay",
                          "Bindoy",
                          "Dauin",
                          "Jimalalud",
                          "La Libertad",
                          "Mabinay",
                          "Manjuyod",
                          "Pamplona",
                          "San Jose",
                          "Santa Catalina",
                          "Siaton",
                          "Sibulan",
                          "Tayasan",
                          "Valencia",
                          "Vallehermoso",
                          "Zamboanguita",
                          "Enrique Villanueva",
                          "Larena",
                          "Lazi",
                          "Maria",
                          "San Juan",
                          "Siquijor",
                          "Arteche",
                          "Balangiga",
                          "Balangkayan",
                          "Can-Avid",
                          "Dolores",
                          "General Macarthur",
                          "Giporlos",
                          "Guiuan",
                          "Hernani",
                          "Jipapad",
                          "Lawaan",
                          "Llorente",
                          "Maslog",
                          "Maydolong",
                          "Mercedes",
                          "Oras",
                          "Quinapondan",
                          "Salcedo",
                          "San Julian",
                          "San Policarpo",
                          "Sulat",
                          "Taft",
                          "Abuyog",
                          "Alangalang",
                          "Albuera",
                          "Babatngon",
                          "Barugo",
                          "Bato",
                          "Burauen",
                          "Calubian",
                          "Capoocan",
                          "Carigara",
                          "Dagami",
                          "Dulag",
                          "Hilongos",
                          "Hindang",
                          "Inopacan",
                          "Isabel",
                          "Jaro",
                          "Javier",
                          "Julita",
                          "Kananga",
                          "La Paz",
                          "Leyte",
                          "Macarthur",
                          "Mahaplag",
                          "Matag-Ob",
                          "Matalom",
                          "Mayorga",
                          "Merida",
                          "Palo",
                          "Palompon",
                          "Pastrana",
                          "San Isidro",
                          "San Miguel",
                          "Santa Fe",
                          "Tabango",
                          "Tabontabon",
                          "Tanauan",
                          "Tolosa",
                          "Tunga",
                          "Villaba",
                          "Allen",
                          "Biri",
                          "Bobon",
                          "Capul",
                          "Catarman",
                          "Catubig",
                          "Gamay",
                          "Laoang",
                          "Lapinig",
                          "Las Navas",
                          "Lavezares",
                          "Mapanas",
                          "Mondragon",
                          "Palapag",
                          "Pambujan",
                          "Rosario",
                          "San Antonio",
                          "San Isidro",
                          "San Jose",
                          "San Roque",
                          "San Vicente",
                          "Silvino Lobos",
                          "Victoria",
                          "Lope De Vega",
                          "Almagro",
                          "Basey",
                          "Calbiga",
                          "Daram",
                          "Gandara",
                          "Hinabangan",
                          "Jiabong",
                          "Marabut",
                          "Matuguinao",
                          "Motiong",
                          "Pinabacdao",
                          "San Jose De Buan",
                          "San Sebastian",
                          "Santa Margarita",
                          "Santa Rita",
                          "Santo NiÃ±o",
                          "Talalora",
                          "Tarangnan",
                          "Villareal",
                          "Paranas",
                          "Zumarraga",
                          "Tagapul-An",
                          "San Jorge",
                          "Pagsanghan",
                          "Anahawan",
                          "Bontoc",
                          "Hinunangan",
                          "Hinundayan",
                          "Libagon",
                          "Liloan",
                          "Macrohon",
                          "Malitbog",
                          "Padre Burgos",
                          "Pintuyan",
                          "Saint Bernard",
                          "San Francisco",
                          "San Juan",
                          "San Ricardo",
                          "Silago",
                          "Sogod",
                          "Tomas Oppus",
                          "Limasawa",
                          "Almeria",
                          "Biliran",
                          "Cabucgayan",
                          "Caibiran",
                          "Culaba",
                          "Kawayan",
                          "Maripipi",
                          "Naval",
                          "Katipunan",
                          "La Libertad",
                          "Labason",
                          "Liloy",
                          "Manukan",
                          "Mutia",
                          "PiÃ±an",
                          "Polanco",
                          "Pres. Manuel a. Roxas",
                          "Rizal",
                          "Salug",
                          "Sergio osmeÃ±a Sr.",
                          "Siayan",
                          "Sibuco",
                          "Sibutad",
                          "Sindangan",
                          "Siocon",
                          "Sirawai",
                          "Tampilisan",
                          "Jose Dalman",
                          "Gutalac",
                          "Baliguian",
                          "Godod",
                          "Bacungan",
                          "Kalawit",
                          "Aurora",
                          "Bayog",
                          "Dimataling",
                          "Dinas",
                          "Dumalinao",
                          "Dumingag",
                          "Kumalarang",
                          "Labangan",
                          "Lapuyan",
                          "Mahayag",
                          "Margosatubig",
                          "Midsalip",
                          "Molave",
                          "Ramon Magsaysay",
                          "San Miguel",
                          "San Pablo",
                          "Tabina",
                          "Tambulig",
                          "Tukuran",
                          "Lakewood",
                          "Josefina",
                          "Pitogo",
                          "Sominot",
                          "Vincenzo a. Sagun",
                          "Guipos",
                          "Tigbao",
                          "Alicia",
                          "Buug",
                          "Diplahan",
                          "Imelda",
                          "Ipil",
                          "Kabasalan",
                          "Mabuhay",
                          "Malangas",
                          "Naga",
                          "Olutanga",
                          "Payao",
                          "Roseller Lim",
                          "Siay",
                          "Talusan",
                          "Titay",
                          "Tungawan",
                          "Baungon",
                          "Damulog",
                          "Dangcagan",
                          "Don Carlos",
                          "Impasug-Ong",
                          "Kadingilan",
                          "Kalilangan",
                          "Kibawe",
                          "Kitaotao",
                          "Lantapan",
                          "Libona",
                          "Malitbog",
                          "Manolo Fortich",
                          "Maramag",
                          "Pangantucan",
                          "Quezon",
                          "San Fernando",
                          "Sumilao",
                          "Talakag",
                          "Cabanglasan",
                          "Catarman",
                          "Guinsiliban",
                          "Mahinog",
                          "Mambajao",
                          "Sagay",
                          "Bacolod",
                          "Baloi",
                          "Baroy",
                          "Kapatagan",
                          "Sultan Naga Dimaporo",
                          "Kauswagan",
                          "Kolambugan",
                          "Lala",
                          "Linamon",
                          "Magsaysay",
                          "Maigo",
                          "Matungao",
                          "Munai",
                          "Nunungan",
                          "Pantao Ragat",
                          "Poona Piagapo",
                          "Salvador",
                          "Sapad",
                          "Tagoloan",
                          "Tangcal",
                          "Tubod",
                          "Pantar",
                          "Aloran",
                          "Baliangao",
                          "Bonifacio",
                          "Calamba",
                          "Clarin",
                          "Concepcion",
                          "Jimenez",
                          "Lopez Jaena",
                          "Panaon",
                          "Plaridel",
                          "Sapang Dalaga",
                          "Sinacaban",
                          "Tudela",
                          "Don Victoriano Chiongbian",
                          "Alubijid",
                          "Balingasag",
                          "Balingoan",
                          "Binuangan",
                          "Claveria",
                          "Gitagum",
                          "Initao",
                          "Jasaan",
                          "Kinoguitan",
                          "Lagonglong",
                          "Laguindingan",
                          "Libertad",
                          "Lugait",
                          "Magsaysay",
                          "Manticao",
                          "Medina",
                          "Naawan",
                          "Opol",
                          "Salay",
                          "Sugbongcogon",
                          "Tagoloan",
                          "Talisayan",
                          "Villanueva",
                          "Asuncion",
                          "Carmen",
                          "Kapalong",
                          "New Corella",
                          "Santo Tomas",
                          "Talaingod",
                          "Braulio E. Dujali",
                          "San Isidro",
                          "Bansalan",
                          "Hagonoy",
                          "Kiblawan",
                          "Magsaysay",
                          "Malalag",
                          "Matanao",
                          "Padada",
                          "Santa Cruz",
                          "Sulop",
                          "Baganga",
                          "Banaybanay",
                          "Boston",
                          "Caraga",
                          "Cateel",
                          "Governor Generoso",
                          "Lupon",
                          "Manay",
                          "San Isidro",
                          "Tarragona",
                          "Compostela",
                          "Laak",
                          "Mabini",
                          "Maco",
                          "Maragusan",
                          "Mawab",
                          "Monkayo",
                          "Montevista",
                          "Nabunturan",
                          "New Bataan",
                          "Pantukan",
                          "Don Marcelino",
                          "Jose Abad Santos",
                          "Malita",
                          "Santa Maria",
                          "Sarangani",
                          "Alamada",
                          "Carmen",
                          "Kabacan",
                          "Libungan",
                          "Magpet",
                          "Makilala",
                          "Matalam",
                          "Midsayap",
                          "M'lang",
                          "Pigkawayan",
                          "Pikit",
                          "President Roxas",
                          "Tulunan",
                          "Antipas",
                          "Banisilan",
                          "Aleosan",
                          "Arakan",
                          "Banga",
                          "Norala",
                          "Polomolok",
                          "Surallah",
                          "Tampakan",
                          "Tantangan",
                          "T'boli",
                          "Tupi",
                          "Santo NiÃ±o",
                          "Lake Sebu",
                          "Bagumbayan",
                          "Columbio",
                          "Esperanza",
                          "Isulan",
                          "Kalamansig",
                          "Lebak",
                          "Lutayan",
                          "Lambayong",
                          "Palimbang",
                          "President Quirino",
                          "Sen. Ninoy Aquino",
                          "Alabel",
                          "Glan",
                          "Kiamba",
                          "Maasim",
                          "Maitum",
                          "Malapatan",
                          "Malungon",
                          "Pateros",
                          "Bangued",
                          "Boliney",
                          "Bucay",
                          "Bucloc",
                          "Daguioman",
                          "Danglas",
                          "Dolores",
                          "La Paz",
                          "Lacub",
                          "Lagangilang",
                          "Lagayan",
                          "Langiden",
                          "Licuan-Baay",
                          "Luba",
                          "Malibcong",
                          "Manabo",
                          "PeÃ±arrubia",
                          "Pidigan",
                          "Pilar",
                          "Sallapadan",
                          "San Isidro",
                          "San Juan",
                          "San Quintin",
                          "Tayum",
                          "Tineg",
                          "Tubo",
                          "Villaviciosa",
                          "Atok",
                          "Bakun",
                          "Bokod",
                          "Buguias",
                          "Itogon",
                          "Kabayan",
                          "Kapangan",
                          "Kibungan",
                          "La Trinidad",
                          "Mankayan",
                          "Sablan",
                          "Tuba",
                          "Tublay",
                          "Banaue",
                          "Hungduan",
                          "Kiangan",
                          "Lagawe",
                          "Lamut",
                          "Mayoyao",
                          "Alfonso Lista",
                          "Aguinaldo",
                          "Hingyon",
                          "Tinoc",
                          "Asipulo",
                          "Balbalan",
                          "Lubuagan",
                          "Pasil",
                          "Pinukpuk",
                          "Rizal",
                          "Tanudan",
                          "Tinglayan",
                          "Barlig",
                          "Bauko",
                          "Besao",
                          "Bontoc",
                          "Natonin",
                          "Paracelis",
                          "Sabangan",
                          "Sadanga",
                          "Sagada",
                          "Tadian",
                          "Calanasan",
                          "Conner",
                          "Flora",
                          "Kabugao",
                          "Luna",
                          "Pudtol",
                          "Santa Marcela",
                          "Buenavista",
                          "Carmen",
                          "Jabonga",
                          "Kitcharao",
                          "Las Nieves",
                          "Magallanes",
                          "Nasipit",
                          "Santiago",
                          "Tubay",
                          "Remedios T. Romualdez",
                          "Bunawan",
                          "Esperanza",
                          "La Paz",
                          "Loreto",
                          "Prosperidad",
                          "Rosario",
                          "San Francisco",
                          "San Luis",
                          "Santa Josefa",
                          "Talacogon",
                          "Trento",
                          "Veruela",
                          "Sibagat",
                          "Alegria",
                          "Bacuag",
                          "Burgos",
                          "Claver",
                          "Dapa",
                          "Del Carmen",
                          "General Luna",
                          "Gigaquit",
                          "Mainit",
                          "Malimono",
                          "Pilar",
                          "Placer",
                          "San Benito",
                          "San Francisco",
                          "San Isidro",
                          "Santa Monica",
                          "Sison",
                          "Socorro",
                          "Tagana-An",
                          "Tubod",
                          "Barobo",
                          "Bayabas",
                          "Cagwait",
                          "Cantilan",
                          "Carmen",
                          "Carrascal",
                          "Cortes",
                          "Hinatuan",
                          "Lanuza",
                          "Lianga",
                          "Lingig",
                          "Madrid",
                          "Marihatag",
                          "San Agustin",
                          "San Miguel",
                          "Tagbina",
                          "Tago",
                          "Basilisa",
                          "Cagdianao",
                          "Dinagat",
                          "Libjo",
                          "Loreto",
                          "San Jose",
                          "Tubajon",
                          "Lantawan",
                          "Maluso",
                          "Sumisip",
                          "Tipo-Tipo",
                          "Tuburan",
                          "Akbar",
                          "Al-Barka",
                          "Hadji Mohammad Ajul",
                          "Ungkaya Pukan",
                          "Hadji Muhtamad",
                          "Tabuan-Lasa",
                          "Bacolod-Kalawi",
                          "Balabagan",
                          "Balindong",
                          "Bayang",
                          "Binidayan",
                          "Bubong",
                          "Butig",
                          "Ganassi",
                          "Kapai",
                          "Lumba-Bayabao",
                          "Lumbatan",
                          "Madalum",
                          "Madamba",
                          "Malabang",
                          "Marantao",
                          "Masiu",
                          "Mulondo",
                          "Pagayawan",
                          "Piagapo",
                          "Poona Bayabao",
                          "Pualas",
                          "Ditsaan-Ramain",
                          "Saguiaran",
                          "Tamparan",
                          "Taraka",
                          "Tubaran",
                          "Tugaya",
                          "Wao",
                          "Marogong",
                          "Calanogas",
                          "Buadiposo-Buntong",
                          "Maguing",
                          "Picong",
                          "Lumbayanague",
                          "Amai Manabilang",
                          "Tagoloan Ii",
                          "Kapatagan",
                          "Sultan Dumalondong",
                          "Lumbaca-Unayan",
                          "Ampatuan",
                          "Buldon",
                          "Buluan",
                          "Datu Paglas",
                          "Datu Piang",
                          "Datu Odin Sinsuat",
                          "Shariff Aguak",
                          "Matanog",
                          "Pagalungan",
                          "Parang",
                          "Sultan Kudarat",
                          "Sultan Sa Barongis",
                          "Kabuntalan",
                          "Upi",
                          "Talayan",
                          "South Upi",
                          "Barira",
                          "Gen. s.k. Pendatun",
                          "Mamasapano",
                          "Talitay",
                          "Pagagawan",
                          "Paglat",
                          "Sultan Mastura",
                          "Guindulungan",
                          "Datu Saudi-Ampatuan",
                          "Datu Unsay",
                          "Datu Abdullah Sangki",
                          "Rajah Buayan",
                          "Datu Blah T. Sinsuat",
                          "Datu Anggal Midtimbang",
                          "Mangudadatu",
                          "Pandag",
                          "Northern Kabuntalan",
                          "Datu Hoffer Ampatuan",
                          "Datu Salibo",
                          "Shariff Saydona Mustapha",
                          "Indanan",
                          "Jolo",
                          "Kalingalan Caluang",
                          "Luuk",
                          "Maimbung",
                          "Hadji Panglima Tahil",
                          "Old Panamao",
                          "Pangutaran",
                          "Parang",
                          "Pata",
                          "Patikul",
                          "Siasi",
                          "Talipao",
                          "Tapul",
                          "Tongkil",
                          "Panglima Estino",
                          "Lugus",
                          "Pandami",
                          "Omar",
                          "Panglima Sugala",
                          "Bongao",
                          "Mapun",
                          "Simunul",
                          "Sitangkai",
                          "South Ubian",
                          "Tandubas",
                          "Turtle Islands",
                          "Languyan",
                          "Sapa-Sapa",
                          "Sibutu"
                        ],
                        dropdownSearchDecoration: const InputDecoration(
                          labelText: "Select your Municipality*",
                        ),
                        onChanged: (newmenu) {
                          setState(() {
                            selectedCity = newmenu.toString();
                          });
                        },
                        showSearchBox: true,
                        searchFieldProps: const TextFieldProps(
                          cursorColor: Colors.blue,
                        ),
                      ),
                    ),
//==============================================================================
                    const SizedBox(height: 100),
                  ],
                ),
              ),
            ),
          ),
          floatingActionButton: ExpandableFab(distance: 120, children: [
            ActionButton(
              icon: const Icon(
                Icons.save,
                color: Colors.white,
                size: 35,
              ),
              onPressed: () {
                // addUser();
              },
            ),
            ActionButton(
              icon: const Icon(
                Icons.update,
                color: Colors.white,
                size: 35,
              ),
              onPressed: () {
                // getUsers();
                Map<String, String> tasks = {
                  'first': firstNameController.text,
                  'middle': middleNameController.text,
                  'surname': surNameController.text,
                  'sex': selectedSex,
                  'bday': birthController.text,
                  'address': addressController.text,
                  'barangay': barangayController.text,
                  'contactNum': contactNumController.text,
                  'region': selectedRegion,
                  'province': selectedProvince,
                  'city': selectedCity,
                  // 'agency': agencyType,
                };

                dbRef
                    .update(tasks)
                    .then((value) => showSnackBar(context, 'Profile Updated'))
                    .catchError((error) => showSnackBar(context, 'Error'));
              },
            ),
            ActionButton(
              icon: const Icon(
                Icons.logout,
                color: Colors.white,
                size: 35,
              ),
              onPressed: () {
                context.read<FirebaseAuthMethods>().signOut(context);
              },
            ),
          ]),
        ),
      );
}

// class GetUserName extends StatelessWidget {
//   final String documentId;

//   GetUserName(this.documentId);

//   @override
//   Widget build(BuildContext context) {
//     CollectionReference users = FirebaseFirestore.instance.collection('users');

//     return FutureBuilder<DocumentSnapshot>(
//       future: users.doc(documentId).get(),
//       builder:
//           (BuildContext context, AsyncSnapshot<DocumentSnapshot> snapshot) {
//         if (snapshot.hasError) {
//           return Text("Something went wrong");
//         }

//         if (snapshot.hasData && !snapshot.data!.exists) {
//           return Text("Document does not exist");
//         }

//         if (snapshot.connectionState == ConnectionState.done) {
//           Map<String, dynamic> data =
//               snapshot.data!.data() as Map<String, dynamic>;
//           return Text("Full Name: ${data['full_name']} ${data['last_name']}");
//         }

//         return Text("loading");
//       },
//     );
//   }
// }

//https://www.youtube.com/watch?v=pAn3-cqJ9MM&t=346s

// class ProfilePage3 extends StatefulWidget {
//   const ProfilePage3({super.key});

//   @override
//   State<ProfilePage3> createState() => _ProfilePageState();
// }

// class _ProfilePageState extends State<ProfilePage3> {

// final uid = FirebaseAuth.instance.currentUser!.uid;
// final email = FirebaseAuth.instance.currentUser!.email;
// final creatinTime = FirebaseAuth.instance.currentUser!.metadata.creationTime;
// final scaffoldKey = GlobalKey<ScaffoldState>();

//   User? user = FirebaseAuth.instance.currentUser;

//   verifyEmail() async {
//     if (user != null && user!.emailVerified) {
//       await user!.sendEmailVerification();
//       showSnackBar(context, "Verification Email has been sent.");

//       // ScaffoldMessenger.of(context).showSnackBar(snackBar(
//       //   backgroundcolor: Colors.black26,
//       //   content: Text('Verification Email has been sent.',
//       //   style: TextStyle(fontSize: 18.0, color: Colors.amber),
//       //   ),);
//       Scaffold(
//         key: scaffoldKey,
//         body: GestureDetector(
//           onTap: () {
//             ScaffoldMessenger.of(context).showSnackBar(SnackBar(
//               content: const Text('snack'),
//               duration: const Duration(seconds: 1),
//               action: SnackBarAction(
//                 label: 'ACTION',
//                 onPressed: () {},
//               ),
//             ));
//           },
//           child: const Text('SHOW SNACK'),
//         ),
//       );
//     }
//   }
// }

// https://stackoverflow.com/questions/66196971/how-to-access-variable-value-from-a-different-screen-in-flutter
//       class Value {
//         static String value;
//         static void setString(String newValue) {
//           value = newValue;
//         }

//         static String getString() {
//           return value;
//         }
//       }

class UserModel {
  String name;
  String age;

  UserModel({required this.name, required this.age});

  UserModel.fromJson(Map<String, dynamic> parsedJSON)
      : name = parsedJSON['first'],
        age = parsedJSON['surname'];
}
