import 'package:alerto24/home/auth/firebase_auth_methods.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';
import 'package:dropdown_search/dropdown_search.dart';

class RegisterPage extends StatefulWidget {
  final String data;

  const RegisterPage({Key? key, required this.data}) : super(key: key);

  @override
  State<RegisterPage> createState() => _RegisterPageState();
}

class _RegisterPageState extends State<RegisterPage> {
  final TextEditingController emailController = TextEditingController();
  final TextEditingController passwordController = TextEditingController();
  final TextEditingController confirmPasswordController =
      TextEditingController();
  final TextEditingController firstNameController = TextEditingController();
  final TextEditingController middleNameController = TextEditingController();
  final TextEditingController surNameController = TextEditingController();
  // final TextEditingController suffixController = TextEditingController();
  final TextEditingController contactNumController = TextEditingController();
  final TextEditingController addressController = TextEditingController();
  final TextEditingController postalCodeController = TextEditingController();
  final TextEditingController regionController = TextEditingController();
  final TextEditingController provinceController = TextEditingController();
  final TextEditingController cityController = TextEditingController();
  final TextEditingController barangayController = TextEditingController();

  DatabaseReference reference =
      FirebaseDatabase.instance.ref().child('address_lookup');

  final List<String> regionList = [
    "Region I",
    "Region II",
    "Region III",
    "Region IV-A",
    "MIMAROPA Region",
    "Region V",
    "Region VI",
    "Region VII",
    "Region VIII",
    "Region IX",
    "Region X",
    "Region XI",
    "Region XII",
    "National Capital Region",
    "Cordillera Administrative Region",
    "Region XIII",
    "Bangsamoro Autonomous Region in Muslim Mindanao"
  ];

  final List<dynamic> cityList = [];
  final List<dynamic> barangayList = [];

  @override
  void dispose() {
    emailController.dispose();
    passwordController.dispose();
    confirmPasswordController.dispose();
    firstNameController.dispose();
    middleNameController.dispose();
    surNameController.dispose();
    // suffixController.dispose();
    contactNumController.dispose();
    addressController.dispose();
    postalCodeController.dispose();
    super.dispose();
  }

  void signUpUser() async {
    FirebaseAuthMethods(FirebaseAuth.instance).signUpWithEmail(
      email: emailController.text,
      password: passwordController.text,
      // first: firstNameController.text,
      // surname: middleNameController.text,
      // middle: surNameController.text,
      // suffix: suffixController.text,
      // contact: contactNumController.text,
      // address: addressController.text,
      // address: postalCodeController.text,
      context: context,
    );
  }

  Widget build(BuildContext context) => WillPopScope(
        onWillPop: () async {
          return true;
        },
        child: Scaffold(
          backgroundColor: Colors.grey[300],
          body: SafeArea(
            child: SingleChildScrollView(
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Container(
                      width: 130,
                      height: 130,
                      decoration: BoxDecoration(
                          border: Border.all(
                              width: 4,
                              color: Theme.of(context).scaffoldBackgroundColor),
                          boxShadow: [
                            BoxShadow(
                                spreadRadius: 2,
                                blurRadius: 10,
                                color: Colors.black.withOpacity(0.1),
                                offset: Offset(0, 10))
                          ],
                          shape: BoxShape.circle,
                          image: const DecorationImage(
                              fit: BoxFit.cover,
                              image: NetworkImage(
                                "https://firebasestorage.googleapis.com/v0/b/schooapp2022.appspot.com/o/images%2FAA-logo.png?alt=media&token=c5accba9-dd82-44a3-9743-05a570330598",
                              ))),
                    ),
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          border: Border.all(color: Colors.white),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.only(left: 20.0),
                          child: TextField(
                            controller: emailController,
                            decoration: const InputDecoration(
                              border: InputBorder.none,
                              hintText: 'Email:*',
                            ),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          border: Border.all(color: Colors.white),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.only(left: 20.0),
                          child: TextFormField(
                            obscureText: true,
                            decoration: const InputDecoration(
                              border: InputBorder.none,
                              hintText: 'Password:*',
                            ),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          border: Border.all(color: Colors.white),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.only(left: 20.0),
                          child: TextFormField(
                            obscureText: true,
                            decoration: const InputDecoration(
                              border: InputBorder.none,
                              hintText: 'Confirm Password:*',
                            ),
                          ),
                        ),
                      ),
                    ),
                    // const SizedBox(height: 10),
                    // Padding(
                    //   padding: const EdgeInsets.symmetric(horizontal: 25.0),
                    //   child: Container(
                    //     decoration: BoxDecoration(
                    //       color: Colors.grey[200],
                    //       border: Border.all(color: Colors.white),
                    //       borderRadius: BorderRadius.circular(12),
                    //     ),
                    //     child: Padding(
                    //       padding: const EdgeInsets.only(left: 20.0),
                    //       child: TextField(
                    //         controller: firstNameController,
                    //         decoration: const InputDecoration(
                    //           border: InputBorder.none,
                    //           hintText: 'First Name:*',
                    //         ),
                    //       ),
                    //     ),
                    //   ),
                    // ),
                    // const SizedBox(height: 10),
                    // Padding(
                    //   padding: const EdgeInsets.symmetric(horizontal: 25.0),
                    //   child: Container(
                    //     decoration: BoxDecoration(
                    //       color: Colors.grey[200],
                    //       border: Border.all(color: Colors.white),
                    //       borderRadius: BorderRadius.circular(12),
                    //     ),
                    //     child: Padding(
                    //       padding: const EdgeInsets.only(left: 20.0),
                    //       child: TextField(
                    //         controller: middleNameController,
                    //         decoration: const InputDecoration(
                    //           border: InputBorder.none,
                    //           hintText: 'Middle Name:*',
                    //         ),
                    //       ),
                    //     ),
                    //   ),
                    // ),
                    // const SizedBox(height: 10),
                    // Padding(
                    //   padding: const EdgeInsets.symmetric(horizontal: 25.0),
                    //   child: Container(
                    //     decoration: BoxDecoration(
                    //       color: Colors.grey[200],
                    //       border: Border.all(color: Colors.white),
                    //       borderRadius: BorderRadius.circular(12),
                    //     ),
                    //     child: Padding(
                    //       padding: const EdgeInsets.only(left: 20.0),
                    //       child: TextField(
                    //         controller: surNameController,
                    //         decoration: const InputDecoration(
                    //           border: InputBorder.none,
                    //           hintText: 'Surname:*',
                    //         ),
                    //       ),
                    //     ),
                    //   ),
                    // ),
                    // const SizedBox(height: 10),
                    // Padding(
                    //   padding: const EdgeInsets.symmetric(horizontal: 25.0),
                    //   child: Container(
                    //     decoration: BoxDecoration(
                    //       color: Colors.grey[200],
                    //       border: Border.all(color: Colors.white),
                    //       borderRadius: BorderRadius.circular(12),
                    //     ),
                    //     child: Padding(
                    //       padding: const EdgeInsets.only(left: 20.0),
                    //       child: TextField(
                    //         controller: suffixController,
                    //         decoration: const InputDecoration(
                    //           border: InputBorder.none,
                    //           hintText: 'Suffix ex. Jr, III, Sr (optional)',
                    //         ),
                    //       ),
                    //     ),
                    //   ),
                    // ),
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          border: Border.all(color: Colors.white),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.only(left: 20.0),
                          child: TextField(
                            controller: contactNumController,
                            decoration: const InputDecoration(
                              border: InputBorder.none,
                              hintText: 'Contact Number:*',
                            ),
                          ),
                        ),
                      ),
                    ),

                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          border: Border.all(color: Colors.white),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.only(left: 20.0),
                          child: TextField(
                            controller: addressController,
                            decoration: const InputDecoration(
                              border: InputBorder.none,
                              hintText: 'Address:*',
                            ),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: Container(
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          border: Border.all(color: Colors.white),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.only(left: 20.0),
                          child: TextField(
                            controller: emailController,
                            decoration: const InputDecoration(
                              border: InputBorder.none,
                              hintText: 'Barangay:*',
                            ),
                          ),
                        ),
                      ),
                    ),
//========================================================================
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: DropdownSearch<String>(
                        mode: Mode.MENU,
                        showSelectedItems: true,
                        items: regionList,
                        dropdownSearchDecoration: const InputDecoration(
                          labelText: "Select your Region*",
                          hintText: "Search Region here...",
                        ),
                        onChanged: itemSelectionChanged,
                        showSearchBox: true,
                        searchFieldProps: const TextFieldProps(
                          cursorColor: Colors.blue,
                        ),
                      ),
                    ),
//========================================================================
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: DropdownSearch<String>(
                        mode: Mode.MENU,
                        showSelectedItems: true,
                        items: const [
                          "Ilocos Norte",
                          "Ilocos Sur",
                          "La Union",
                          "Pangasinan",
                          "Batanes",
                          "Cagayan",
                          "Isabela",
                          "Nueva Vizcaya",
                          "Quirino",
                          "Bataan",
                          "Bulacan",
                          "Nueva Ecija",
                          "Pampanga",
                          "Tarlac",
                          "Zambales",
                          "Aurora",
                          "Batangas",
                          "Cavite",
                          "Laguna",
                          "Quezon",
                          "Rizal",
                          "Marinduque",
                          "Occidental Mindoro",
                          "Oriental Mindoro",
                          "Palawan",
                          "Romblon",
                          "Albay",
                          "Camarines Norte",
                          "Camarines Sur",
                          "Catanduanes",
                          "Masbate",
                          "Sorsogon",
                          "Aklan",
                          "Antique",
                          "Capiz",
                          "Iloilo",
                          "Negros Occidental",
                          "Guimaras",
                          "Bohol",
                          "Cebu",
                          "Negros Oriental",
                          "Siquijor",
                          "Eastern Samar",
                          "Leyte",
                          "Northern Samar",
                          "Samar",
                          "Southern Leyte",
                          "Biliran",
                          "Zamboanga Del Norte",
                          "Zamboanga Del Sur",
                          "Zamboanga Sibugay",
                          "Bukidnon",
                          "Camiguin",
                          "Lanao Del Norte",
                          "Misamis Occidental",
                          "Misamis Oriental",
                          "Davao Del Norte",
                          "Davao Del Sur",
                          "Davao Oriental",
                          "Davao De Oro",
                          "Davao Occidental",
                          "Cotabato",
                          "South Cotabato",
                          "Sultan Kudarat",
                          "Sarangani",
                          "Abra",
                          "Benguet",
                          "Ifugao",
                          "Kalinga",
                          "Mountain Province",
                          "Apayao",
                          "Agusan Del Norte",
                          "Agusan Del Sur",
                          "Surigao Del Norte",
                          "Surigao Del Sur",
                          "Dinagat Islands",
                          "Basilan",
                          "Lanao Del Sur",
                          "Maguindanao",
                          "Sulu",
                          "Tawi-Tawi"
                        ],
                        dropdownSearchDecoration: const InputDecoration(
                          labelText: "Select your Province*",
                          // hintText: "country in menu mode",
                        ),
                        onChanged: itemSelectionChanged,
                        showSearchBox: true,
                        searchFieldProps: const TextFieldProps(
                          cursorColor: Colors.blue,
                        ),
                      ),
                    ),
//========================================================================
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: DropdownSearch<String>(
                        mode: Mode.MENU,
                        showSelectedItems: true,
                        items: const [
                          "Adams",
                          "Bacarra",
                          "Badoc",
                          "Bangui",
                          "Burgos",
                          "Carasi",
                          "Currimao",
                          "Dingras",
                          "Dumalneg",
                          "Banna",
                          "Marcos",
                          "Nueva Era",
                          "Pagudpud",
                          "Paoay",
                          "Pasuquin",
                          "Piddig",
                          "Pinili",
                          "San Nicolas",
                          "Sarrat",
                          "Solsona",
                          "Vintar",
                          "Alilem",
                          "Banayoyo",
                          "Bantay",
                          "Burgos",
                          "Cabugao",
                          "Caoayan",
                          "Cervantes",
                          "Galimuyod",
                          "Gregorio Del Pilar",
                          "Lidlidda",
                          "Magsingal",
                          "Nagbukel",
                          "Narvacan",
                          "Quirino",
                          "Salcedo",
                          "San Emilio",
                          "San Esteban",
                          "San Ildefonso",
                          "San Juan",
                          "San Vicente",
                          "Santa",
                          "Santa Catalina",
                          "Santa Cruz",
                          "Santa Lucia",
                          "Santa Maria",
                          "Santiago",
                          "Santo Domingo",
                          "Sigay",
                          "Sinait",
                          "Sugpon",
                          "Suyo",
                          "Tagudin",
                          "Agoo",
                          "Aringay",
                          "Bacnotan",
                          "Bagulin",
                          "Balaoan",
                          "Bangar",
                          "Bauang",
                          "Burgos",
                          "Caba",
                          "Luna",
                          "Naguilian",
                          "Pugo",
                          "Rosario",
                          "San Gabriel",
                          "San Juan",
                          "Santo Tomas",
                          "Santol",
                          "Sudipen",
                          "Tubao",
                          "Agno",
                          "Aguilar",
                          "Alcala",
                          "Anda",
                          "Asingan",
                          "Balungao",
                          "Bani",
                          "Basista",
                          "Bautista",
                          "Bayambang",
                          "Binalonan",
                          "Binmaley",
                          "Bolinao",
                          "Bugallon",
                          "Burgos",
                          "Calasiao",
                          "Dasol",
                          "Infanta",
                          "Labrador",
                          "Lingayen",
                          "Mabini",
                          "Malasiqui",
                          "Manaoag",
                          "Mangaldan",
                          "Mangatarem",
                          "Mapandan",
                          "Natividad",
                          "Pozorrubio",
                          "Rosales",
                          "San Fabian",
                          "San Jacinto",
                          "San Manuel",
                          "San Nicolas",
                          "San Quintin",
                          "Santa Barbara",
                          "Santa Maria",
                          "Santo Tomas",
                          "Sison",
                          "Sual",
                          "Tayug",
                          "Umingan",
                          "Urbiztondo",
                          "Villasis",
                          "Laoac",
                          "Basco",
                          "Itbayat",
                          "Ivana",
                          "Mahatao",
                          "Sabtang",
                          "Uyugan",
                          "Abulug",
                          "Alcala",
                          "Allacapan",
                          "Amulung",
                          "Aparri",
                          "Baggao",
                          "Ballesteros",
                          "Buguey",
                          "Calayan",
                          "Camalaniugan",
                          "Claveria",
                          "Enrile",
                          "Gattaran",
                          "Gonzaga",
                          "Iguig",
                          "Lal-Lo",
                          "Lasam",
                          "Pamplona",
                          "PeÃ±ablanca",
                          "Piat",
                          "Rizal",
                          "Sanchez-Mira",
                          "Santa Ana",
                          "Santa Praxedes",
                          "Santa Teresita",
                          "Santo NiÃ±o",
                          "Solana",
                          "Tuao",
                          "Alicia",
                          "Angadanan",
                          "Aurora",
                          "Benito Soliven",
                          "Burgos",
                          "Cabagan",
                          "Cabatuan",
                          "Cordon",
                          "Dinapigue",
                          "Divilacan",
                          "Echague",
                          "Gamu",
                          "Jones",
                          "Luna",
                          "Maconacon",
                          "Delfin Albano",
                          "Mallig",
                          "Naguilian",
                          "Palanan",
                          "Quezon",
                          "Quirino",
                          "Ramon",
                          "Reina Mercedes",
                          "Roxas",
                          "San Agustin",
                          "San Guillermo",
                          "San Isidro",
                          "San Manuel",
                          "San Mariano",
                          "San Mateo",
                          "San Pablo",
                          "Santa Maria",
                          "Santo Tomas",
                          "Tumauini",
                          "Ambaguio",
                          "Aritao",
                          "Bagabag",
                          "Bambang",
                          "Bayombong",
                          "Diadi",
                          "Dupax Del Norte",
                          "Dupax Del Sur",
                          "Kasibu",
                          "Kayapa",
                          "Quezon",
                          "Santa Fe",
                          "Solano",
                          "Villaverde",
                          "Alfonso Castaneda",
                          "Aglipay",
                          "Cabarroguis",
                          "Diffun",
                          "Maddela",
                          "Saguday",
                          "Nagtipunan",
                          "Abucay",
                          "Bagac",
                          "Dinalupihan",
                          "Hermosa",
                          "Limay",
                          "Mariveles",
                          "Morong",
                          "Orani",
                          "Orion",
                          "Pilar",
                          "Samal",
                          "Angat",
                          "Balagtas",
                          "Baliuag",
                          "Bocaue",
                          "Bulacan",
                          "Bustos",
                          "Calumpit",
                          "Guiguinto",
                          "Hagonoy",
                          "Marilao",
                          "Norzagaray",
                          "Obando",
                          "Pandi",
                          "Paombong",
                          "Plaridel",
                          "Pulilan",
                          "San Ildefonso",
                          "San Miguel",
                          "San Rafael",
                          "Santa Maria",
                          "DoÃ±a Remedios Trinidad",
                          "Aliaga",
                          "Bongabon",
                          "Cabiao",
                          "Carranglan",
                          "Cuyapo",
                          "Gabaldon",
                          "General Mamerto Natividad",
                          "General Tinio",
                          "Guimba",
                          "Jaen",
                          "Laur",
                          "Licab",
                          "Llanera",
                          "Lupao",
                          "Nampicuan",
                          "Pantabangan",
                          "PeÃ±aranda",
                          "Quezon",
                          "Rizal",
                          "San Antonio",
                          "San Isidro",
                          "San Leonardo",
                          "Santa Rosa",
                          "Santo Domingo",
                          "Talavera",
                          "Talugtug",
                          "Zaragoza",
                          "Apalit",
                          "Arayat",
                          "Bacolor",
                          "Candaba",
                          "Floridablanca",
                          "Guagua",
                          "Lubao",
                          "Macabebe",
                          "Magalang",
                          "Masantol",
                          "Mexico",
                          "Minalin",
                          "Porac",
                          "San Luis",
                          "San Simon",
                          "Santa Ana",
                          "Santa Rita",
                          "Sto. Tomas",
                          "Sasmuan",
                          "Anao",
                          "Bamban",
                          "Camiling",
                          "Capas",
                          "Concepcion",
                          "Gerona",
                          "La Paz",
                          "Mayantoc",
                          "Moncada",
                          "Paniqui",
                          "Pura",
                          "Ramos",
                          "San Clemente",
                          "San Manuel",
                          "Santa Ignacia",
                          "Victoria",
                          "San Jose",
                          "Botolan",
                          "Cabangan",
                          "Candelaria",
                          "Castillejos",
                          "Iba",
                          "Masinloc",
                          "Palauig",
                          "San Antonio",
                          "San Felipe",
                          "San Marcelino",
                          "San Narciso",
                          "Santa Cruz",
                          "Subic",
                          "Baler",
                          "Casiguran",
                          "Dilasag",
                          "Dinalungan",
                          "Dingalan",
                          "Dipaculao",
                          "Maria Aurora",
                          "San Luis",
                          "Agoncillo",
                          "Alitagtag",
                          "Balayan",
                          "Balete",
                          "Bauan",
                          "Calaca",
                          "Calatagan",
                          "Cuenca",
                          "Ibaan",
                          "Laurel",
                          "Lemery",
                          "Lian",
                          "Lobo",
                          "Mabini",
                          "Malvar",
                          "Mataasnakahoy",
                          "Nasugbu",
                          "Padre Garcia",
                          "Rosario",
                          "San Jose",
                          "San Juan",
                          "San Luis",
                          "San Nicolas",
                          "San Pascual",
                          "Santa Teresita",
                          "Taal",
                          "Talisay",
                          "Taysan",
                          "Tingloy",
                          "Tuy",
                          "Alfonso",
                          "Amadeo",
                          "Carmona",
                          "General Emilio Aguinaldo",
                          "Indang",
                          "Kawit",
                          "Magallanes",
                          "Maragondon",
                          "Mendez",
                          "Naic",
                          "Noveleta",
                          "Rosario",
                          "Silang",
                          "Tanza",
                          "Ternate",
                          "Gen. Mariano Alvarez",
                          "Alaminos",
                          "Bay",
                          "Calauan",
                          "Cavinti",
                          "Famy",
                          "Kalayaan",
                          "Liliw",
                          "Los Baños",
                          "Luisiana",
                          "Lumban",
                          "Mabitac",
                          "Magdalena",
                          "Majayjay",
                          "Nagcarlan",
                          "Paete",
                          "Pagsanjan",
                          "Pakil",
                          "Pangil",
                          "Pila",
                          "Rizal",
                          "Santa Cruz",
                          "Santa Maria",
                          "Siniloan",
                          "Victoria",
                          "Agdangan",
                          "Alabat",
                          "Atimonan",
                          "Buenavista",
                          "Burdeos",
                          "Calauag",
                          "Candelaria",
                          "Catanauan",
                          "Dolores",
                          "General Luna",
                          "General Nakar",
                          "Guinayangan",
                          "Gumaca",
                          "Infanta",
                          "Jomalig",
                          "Lopez",
                          "Lucban",
                          "Macalelon",
                          "Mauban",
                          "Mulanay",
                          "Padre Burgos",
                          "Pagbilao",
                          "Panukulan",
                          "Patnanungan",
                          "Perez",
                          "Pitogo",
                          "Plaridel",
                          "Polillo",
                          "Quezon",
                          "Real",
                          "Sampaloc",
                          "San Andres",
                          "San Antonio",
                          "San Francisco",
                          "San Narciso",
                          "Sariaya",
                          "Tagkawayan",
                          "Tiaong",
                          "Unisan",
                          "Angono",
                          "Baras",
                          "Binangonan",
                          "Cainta",
                          "Cardona",
                          "Jala-Jala",
                          "Rodriguez",
                          "Morong",
                          "Pililla",
                          "San Mateo",
                          "Tanay",
                          "Taytay",
                          "Teresa",
                          "Boac",
                          "Buenavista",
                          "Gasan",
                          "Mogpog",
                          "Santa Cruz",
                          "Torrijos",
                          "Abra De Ilog",
                          "Calintaan",
                          "Looc",
                          "Lubang",
                          "Magsaysay",
                          "Mamburao",
                          "Paluan",
                          "Rizal",
                          "Sablayan",
                          "San Jose",
                          "Santa Cruz",
                          "Baco",
                          "Bansud",
                          "Bongabong",
                          "Bulalacao",
                          "Gloria",
                          "Mansalay",
                          "Naujan",
                          "Pinamalayan",
                          "Pola",
                          "Puerto Galera",
                          "Roxas",
                          "San Teodoro",
                          "Socorro",
                          "Victoria",
                          "Aborlan",
                          "Agutaya",
                          "Araceli",
                          "Balabac",
                          "Bataraza",
                          "Brooke's Point",
                          "Busuanga",
                          "Cagayancillo",
                          "Coron",
                          "Cuyo",
                          "Dumaran",
                          "El Nido",
                          "Linapacan",
                          "Magsaysay",
                          "Narra",
                          "Quezon",
                          "Roxas",
                          "San Vicente",
                          "Taytay",
                          "Kalayaan",
                          "Culion",
                          "Rizal",
                          "Sofronio EspaÃ±ola",
                          "Alcantara",
                          "Banton",
                          "Cajidiocan",
                          "Calatrava",
                          "Concepcion",
                          "Corcuera",
                          "Looc",
                          "Magdiwang",
                          "Odiongan",
                          "Romblon",
                          "San Agustin",
                          "San Andres",
                          "San Fernando",
                          "San Jose",
                          "Santa Fe",
                          "Ferrol",
                          "Santa Maria",
                          "Bacacay",
                          "Camalig",
                          "Daraga",
                          "Guinobatan",
                          "Jovellar",
                          "Libon",
                          "Malilipot",
                          "Malinao",
                          "Manito",
                          "Oas",
                          "Pio Duran",
                          "Polangui",
                          "Rapu-Rapu",
                          "Santo Domingo",
                          "Tiwi",
                          "Basud",
                          "Capalonga",
                          "Daet",
                          "San Lorenzo Ruiz",
                          "Jose Panganiban",
                          "Labo",
                          "Mercedes",
                          "Paracale",
                          "San Vicente",
                          "Santa Elena",
                          "Talisay",
                          "Vinzons",
                          "Baao",
                          "Balatan",
                          "Bato",
                          "Bombon",
                          "Buhi",
                          "Bula",
                          "Cabusao",
                          "Calabanga",
                          "Camaligan",
                          "Canaman",
                          "Caramoan",
                          "Del Gallego",
                          "Gainza",
                          "Garchitorena",
                          "Goa",
                          "Lagonoy",
                          "Libmanan",
                          "Lupi",
                          "Magarao",
                          "Milaor",
                          "Minalabac",
                          "Nabua",
                          "Ocampo",
                          "Pamplona",
                          "Pasacao",
                          "Pili",
                          "Presentacion",
                          "Ragay",
                          "SagÃ±ay",
                          "San Fernando",
                          "San Jose",
                          "Sipocot",
                          "Siruma",
                          "Tigaon",
                          "Tinambac",
                          "Bagamanoc",
                          "Baras",
                          "Bato",
                          "Caramoran",
                          "Gigmoto",
                          "Pandan",
                          "Panganiban",
                          "San Andres",
                          "San Miguel",
                          "Viga",
                          "Virac",
                          "Aroroy",
                          "Baleno",
                          "Balud",
                          "Batuan",
                          "Cataingan",
                          "Cawayan",
                          "Claveria",
                          "Dimasalang",
                          "Esperanza",
                          "Mandaon",
                          "Milagros",
                          "Mobo",
                          "Monreal",
                          "Palanas",
                          "Pio v. Corpuz",
                          "Placer",
                          "San Fernando",
                          "San Jacinto",
                          "San Pascual",
                          "Uson",
                          "Barcelona",
                          "Bulan",
                          "Bulusan",
                          "Casiguran",
                          "Castilla",
                          "Donsol",
                          "Gubat",
                          "Irosin",
                          "Juban",
                          "Magallanes",
                          "Matnog",
                          "Pilar",
                          "Prieto Diaz",
                          "Santa Magdalena",
                          "Altavas",
                          "Balete",
                          "Banga",
                          "Batan",
                          "Buruanga",
                          "Ibajay",
                          "Kalibo",
                          "Lezo",
                          "Libacao",
                          "Madalag",
                          "Makato",
                          "Malay",
                          "Malinao",
                          "Nabas",
                          "New Washington",
                          "Numancia",
                          "Tangalan",
                          "Anini-Y",
                          "Barbaza",
                          "Belison",
                          "Bugasong",
                          "Caluya",
                          "Culasi",
                          "Tobias Fornier",
                          "Hamtic",
                          "Laua-An",
                          "Libertad",
                          "Pandan",
                          "Patnongon",
                          "San Jose",
                          "San Remigio",
                          "Sebaste",
                          "Sibalom",
                          "Tibiao",
                          "Valderrama",
                          "Cuartero",
                          "Dao",
                          "Dumalag",
                          "Dumarao",
                          "Ivisan",
                          "Jamindan",
                          "Ma-Ayon",
                          "Mambusao",
                          "Panay",
                          "Panitan",
                          "Pilar",
                          "Pontevedra",
                          "President Roxas",
                          "Sapi-An",
                          "Sigma",
                          "Tapaz",
                          "Ajuy",
                          "Alimodian",
                          "Anilao",
                          "Badiangan",
                          "Balasan",
                          "Banate",
                          "Barotac Nuevo",
                          "Barotac Viejo",
                          "Batad",
                          "Bingawan",
                          "Cabatuan",
                          "Calinog",
                          "Carles",
                          "Concepcion",
                          "Dingle",
                          "DueÃ±as",
                          "Dumangas",
                          "Estancia",
                          "Guimbal",
                          "Igbaras",
                          "Janiuay",
                          "Lambunao",
                          "Leganes",
                          "Lemery",
                          "Leon",
                          "Maasin",
                          "Miagao",
                          "Mina",
                          "New Lucena",
                          "Oton",
                          "Pavia",
                          "Pototan",
                          "San Dionisio",
                          "San Enrique",
                          "San Joaquin",
                          "San Miguel",
                          "San Rafael",
                          "Santa Barbara",
                          "Sara",
                          "Tigbauan",
                          "Tubungan",
                          "Zarraga",
                          "Binalbagan",
                          "Calatrava",
                          "Candoni",
                          "Cauayan",
                          "Enrique B. Magalona",
                          "Hinigaran",
                          "Hinoba-An",
                          "Ilog",
                          "Isabela",
                          "La Castellana",
                          "Manapla",
                          "Moises Padilla",
                          "Murcia",
                          "Pontevedra",
                          "Pulupandan",
                          "San Enrique",
                          "Toboso",
                          "Valladolid",
                          "Salvador Benedicto",
                          "Buenavista",
                          "Jordan",
                          "Nueva Valencia",
                          "San Lorenzo",
                          "Sibunag",
                          "Alburquerque",
                          "Alicia",
                          "Anda",
                          "Antequera",
                          "Baclayon",
                          "Balilihan",
                          "Batuan",
                          "Bilar",
                          "Buenavista",
                          "Calape",
                          "Candijay",
                          "Carmen",
                          "Catigbian",
                          "Clarin",
                          "Corella",
                          "Cortes",
                          "Dagohoy",
                          "Danao",
                          "Dauis",
                          "Dimiao",
                          "Duero",
                          "Garcia Hernandez",
                          "Guindulman",
                          "Inabanga",
                          "Jagna",
                          "Getafe",
                          "Lila",
                          "Loay",
                          "Loboc",
                          "Loon",
                          "Mabini",
                          "Maribojoc",
                          "Panglao",
                          "Pilar",
                          "President Carlos P. Garcia",
                          "Sagbayan",
                          "San Isidro",
                          "San Miguel",
                          "Sevilla",
                          "Sierra Bullones",
                          "Sikatuna",
                          "Talibon",
                          "Trinidad",
                          "Tubigon",
                          "Ubay",
                          "Valencia",
                          "Bien Unido",
                          "Alcantara",
                          "Alcoy",
                          "Alegria",
                          "Aloguinsan",
                          "Argao",
                          "Asturias",
                          "Badian",
                          "Balamban",
                          "Bantayan",
                          "Barili",
                          "Boljoon",
                          "Borbon",
                          "Carmen",
                          "Catmon",
                          "Compostela",
                          "Consolacion",
                          "Cordova",
                          "Daanbantayan",
                          "Dalaguete",
                          "Dumanjug",
                          "Ginatilan",
                          "Liloan",
                          "Madridejos",
                          "Malabuyoc",
                          "Medellin",
                          "Minglanilla",
                          "Moalboal",
                          "Oslob",
                          "Pilar",
                          "Pinamungajan",
                          "Poro",
                          "Ronda",
                          "Samboan",
                          "San Fernando",
                          "San Francisco",
                          "San Remigio",
                          "Santa Fe",
                          "Santander",
                          "Sibonga",
                          "Sogod",
                          "Tabogon",
                          "Tabuelan",
                          "Tuburan",
                          "Tudela",
                          "Amlan",
                          "Ayungon",
                          "Bacong",
                          "Basay",
                          "Bindoy",
                          "Dauin",
                          "Jimalalud",
                          "La Libertad",
                          "Mabinay",
                          "Manjuyod",
                          "Pamplona",
                          "San Jose",
                          "Santa Catalina",
                          "Siaton",
                          "Sibulan",
                          "Tayasan",
                          "Valencia",
                          "Vallehermoso",
                          "Zamboanguita",
                          "Enrique Villanueva",
                          "Larena",
                          "Lazi",
                          "Maria",
                          "San Juan",
                          "Siquijor",
                          "Arteche",
                          "Balangiga",
                          "Balangkayan",
                          "Can-Avid",
                          "Dolores",
                          "General Macarthur",
                          "Giporlos",
                          "Guiuan",
                          "Hernani",
                          "Jipapad",
                          "Lawaan",
                          "Llorente",
                          "Maslog",
                          "Maydolong",
                          "Mercedes",
                          "Oras",
                          "Quinapondan",
                          "Salcedo",
                          "San Julian",
                          "San Policarpo",
                          "Sulat",
                          "Taft",
                          "Abuyog",
                          "Alangalang",
                          "Albuera",
                          "Babatngon",
                          "Barugo",
                          "Bato",
                          "Burauen",
                          "Calubian",
                          "Capoocan",
                          "Carigara",
                          "Dagami",
                          "Dulag",
                          "Hilongos",
                          "Hindang",
                          "Inopacan",
                          "Isabel",
                          "Jaro",
                          "Javier",
                          "Julita",
                          "Kananga",
                          "La Paz",
                          "Leyte",
                          "Macarthur",
                          "Mahaplag",
                          "Matag-Ob",
                          "Matalom",
                          "Mayorga",
                          "Merida",
                          "Palo",
                          "Palompon",
                          "Pastrana",
                          "San Isidro",
                          "San Miguel",
                          "Santa Fe",
                          "Tabango",
                          "Tabontabon",
                          "Tanauan",
                          "Tolosa",
                          "Tunga",
                          "Villaba",
                          "Allen",
                          "Biri",
                          "Bobon",
                          "Capul",
                          "Catarman",
                          "Catubig",
                          "Gamay",
                          "Laoang",
                          "Lapinig",
                          "Las Navas",
                          "Lavezares",
                          "Mapanas",
                          "Mondragon",
                          "Palapag",
                          "Pambujan",
                          "Rosario",
                          "San Antonio",
                          "San Isidro",
                          "San Jose",
                          "San Roque",
                          "San Vicente",
                          "Silvino Lobos",
                          "Victoria",
                          "Lope De Vega",
                          "Almagro",
                          "Basey",
                          "Calbiga",
                          "Daram",
                          "Gandara",
                          "Hinabangan",
                          "Jiabong",
                          "Marabut",
                          "Matuguinao",
                          "Motiong",
                          "Pinabacdao",
                          "San Jose De Buan",
                          "San Sebastian",
                          "Santa Margarita",
                          "Santa Rita",
                          "Santo NiÃ±o",
                          "Talalora",
                          "Tarangnan",
                          "Villareal",
                          "Paranas",
                          "Zumarraga",
                          "Tagapul-An",
                          "San Jorge",
                          "Pagsanghan",
                          "Anahawan",
                          "Bontoc",
                          "Hinunangan",
                          "Hinundayan",
                          "Libagon",
                          "Liloan",
                          "Macrohon",
                          "Malitbog",
                          "Padre Burgos",
                          "Pintuyan",
                          "Saint Bernard",
                          "San Francisco",
                          "San Juan",
                          "San Ricardo",
                          "Silago",
                          "Sogod",
                          "Tomas Oppus",
                          "Limasawa",
                          "Almeria",
                          "Biliran",
                          "Cabucgayan",
                          "Caibiran",
                          "Culaba",
                          "Kawayan",
                          "Maripipi",
                          "Naval",
                          "Katipunan",
                          "La Libertad",
                          "Labason",
                          "Liloy",
                          "Manukan",
                          "Mutia",
                          "PiÃ±an",
                          "Polanco",
                          "Pres. Manuel a. Roxas",
                          "Rizal",
                          "Salug",
                          "Sergio osmeÃ±a Sr.",
                          "Siayan",
                          "Sibuco",
                          "Sibutad",
                          "Sindangan",
                          "Siocon",
                          "Sirawai",
                          "Tampilisan",
                          "Jose Dalman",
                          "Gutalac",
                          "Baliguian",
                          "Godod",
                          "Bacungan",
                          "Kalawit",
                          "Aurora",
                          "Bayog",
                          "Dimataling",
                          "Dinas",
                          "Dumalinao",
                          "Dumingag",
                          "Kumalarang",
                          "Labangan",
                          "Lapuyan",
                          "Mahayag",
                          "Margosatubig",
                          "Midsalip",
                          "Molave",
                          "Ramon Magsaysay",
                          "San Miguel",
                          "San Pablo",
                          "Tabina",
                          "Tambulig",
                          "Tukuran",
                          "Lakewood",
                          "Josefina",
                          "Pitogo",
                          "Sominot",
                          "Vincenzo a. Sagun",
                          "Guipos",
                          "Tigbao",
                          "Alicia",
                          "Buug",
                          "Diplahan",
                          "Imelda",
                          "Ipil",
                          "Kabasalan",
                          "Mabuhay",
                          "Malangas",
                          "Naga",
                          "Olutanga",
                          "Payao",
                          "Roseller Lim",
                          "Siay",
                          "Talusan",
                          "Titay",
                          "Tungawan",
                          "Baungon",
                          "Damulog",
                          "Dangcagan",
                          "Don Carlos",
                          "Impasug-Ong",
                          "Kadingilan",
                          "Kalilangan",
                          "Kibawe",
                          "Kitaotao",
                          "Lantapan",
                          "Libona",
                          "Malitbog",
                          "Manolo Fortich",
                          "Maramag",
                          "Pangantucan",
                          "Quezon",
                          "San Fernando",
                          "Sumilao",
                          "Talakag",
                          "Cabanglasan",
                          "Catarman",
                          "Guinsiliban",
                          "Mahinog",
                          "Mambajao",
                          "Sagay",
                          "Bacolod",
                          "Baloi",
                          "Baroy",
                          "Kapatagan",
                          "Sultan Naga Dimaporo",
                          "Kauswagan",
                          "Kolambugan",
                          "Lala",
                          "Linamon",
                          "Magsaysay",
                          "Maigo",
                          "Matungao",
                          "Munai",
                          "Nunungan",
                          "Pantao Ragat",
                          "Poona Piagapo",
                          "Salvador",
                          "Sapad",
                          "Tagoloan",
                          "Tangcal",
                          "Tubod",
                          "Pantar",
                          "Aloran",
                          "Baliangao",
                          "Bonifacio",
                          "Calamba",
                          "Clarin",
                          "Concepcion",
                          "Jimenez",
                          "Lopez Jaena",
                          "Panaon",
                          "Plaridel",
                          "Sapang Dalaga",
                          "Sinacaban",
                          "Tudela",
                          "Don Victoriano Chiongbian",
                          "Alubijid",
                          "Balingasag",
                          "Balingoan",
                          "Binuangan",
                          "Claveria",
                          "Gitagum",
                          "Initao",
                          "Jasaan",
                          "Kinoguitan",
                          "Lagonglong",
                          "Laguindingan",
                          "Libertad",
                          "Lugait",
                          "Magsaysay",
                          "Manticao",
                          "Medina",
                          "Naawan",
                          "Opol",
                          "Salay",
                          "Sugbongcogon",
                          "Tagoloan",
                          "Talisayan",
                          "Villanueva",
                          "Asuncion",
                          "Carmen",
                          "Kapalong",
                          "New Corella",
                          "Santo Tomas",
                          "Talaingod",
                          "Braulio E. Dujali",
                          "San Isidro",
                          "Bansalan",
                          "Hagonoy",
                          "Kiblawan",
                          "Magsaysay",
                          "Malalag",
                          "Matanao",
                          "Padada",
                          "Santa Cruz",
                          "Sulop",
                          "Baganga",
                          "Banaybanay",
                          "Boston",
                          "Caraga",
                          "Cateel",
                          "Governor Generoso",
                          "Lupon",
                          "Manay",
                          "San Isidro",
                          "Tarragona",
                          "Compostela",
                          "Laak",
                          "Mabini",
                          "Maco",
                          "Maragusan",
                          "Mawab",
                          "Monkayo",
                          "Montevista",
                          "Nabunturan",
                          "New Bataan",
                          "Pantukan",
                          "Don Marcelino",
                          "Jose Abad Santos",
                          "Malita",
                          "Santa Maria",
                          "Sarangani",
                          "Alamada",
                          "Carmen",
                          "Kabacan",
                          "Libungan",
                          "Magpet",
                          "Makilala",
                          "Matalam",
                          "Midsayap",
                          "M'lang",
                          "Pigkawayan",
                          "Pikit",
                          "President Roxas",
                          "Tulunan",
                          "Antipas",
                          "Banisilan",
                          "Aleosan",
                          "Arakan",
                          "Banga",
                          "Norala",
                          "Polomolok",
                          "Surallah",
                          "Tampakan",
                          "Tantangan",
                          "T'boli",
                          "Tupi",
                          "Santo NiÃ±o",
                          "Lake Sebu",
                          "Bagumbayan",
                          "Columbio",
                          "Esperanza",
                          "Isulan",
                          "Kalamansig",
                          "Lebak",
                          "Lutayan",
                          "Lambayong",
                          "Palimbang",
                          "President Quirino",
                          "Sen. Ninoy Aquino",
                          "Alabel",
                          "Glan",
                          "Kiamba",
                          "Maasim",
                          "Maitum",
                          "Malapatan",
                          "Malungon",
                          "Pateros",
                          "Bangued",
                          "Boliney",
                          "Bucay",
                          "Bucloc",
                          "Daguioman",
                          "Danglas",
                          "Dolores",
                          "La Paz",
                          "Lacub",
                          "Lagangilang",
                          "Lagayan",
                          "Langiden",
                          "Licuan-Baay",
                          "Luba",
                          "Malibcong",
                          "Manabo",
                          "PeÃ±arrubia",
                          "Pidigan",
                          "Pilar",
                          "Sallapadan",
                          "San Isidro",
                          "San Juan",
                          "San Quintin",
                          "Tayum",
                          "Tineg",
                          "Tubo",
                          "Villaviciosa",
                          "Atok",
                          "Bakun",
                          "Bokod",
                          "Buguias",
                          "Itogon",
                          "Kabayan",
                          "Kapangan",
                          "Kibungan",
                          "La Trinidad",
                          "Mankayan",
                          "Sablan",
                          "Tuba",
                          "Tublay",
                          "Banaue",
                          "Hungduan",
                          "Kiangan",
                          "Lagawe",
                          "Lamut",
                          "Mayoyao",
                          "Alfonso Lista",
                          "Aguinaldo",
                          "Hingyon",
                          "Tinoc",
                          "Asipulo",
                          "Balbalan",
                          "Lubuagan",
                          "Pasil",
                          "Pinukpuk",
                          "Rizal",
                          "Tanudan",
                          "Tinglayan",
                          "Barlig",
                          "Bauko",
                          "Besao",
                          "Bontoc",
                          "Natonin",
                          "Paracelis",
                          "Sabangan",
                          "Sadanga",
                          "Sagada",
                          "Tadian",
                          "Calanasan",
                          "Conner",
                          "Flora",
                          "Kabugao",
                          "Luna",
                          "Pudtol",
                          "Santa Marcela",
                          "Buenavista",
                          "Carmen",
                          "Jabonga",
                          "Kitcharao",
                          "Las Nieves",
                          "Magallanes",
                          "Nasipit",
                          "Santiago",
                          "Tubay",
                          "Remedios T. Romualdez",
                          "Bunawan",
                          "Esperanza",
                          "La Paz",
                          "Loreto",
                          "Prosperidad",
                          "Rosario",
                          "San Francisco",
                          "San Luis",
                          "Santa Josefa",
                          "Talacogon",
                          "Trento",
                          "Veruela",
                          "Sibagat",
                          "Alegria",
                          "Bacuag",
                          "Burgos",
                          "Claver",
                          "Dapa",
                          "Del Carmen",
                          "General Luna",
                          "Gigaquit",
                          "Mainit",
                          "Malimono",
                          "Pilar",
                          "Placer",
                          "San Benito",
                          "San Francisco",
                          "San Isidro",
                          "Santa Monica",
                          "Sison",
                          "Socorro",
                          "Tagana-An",
                          "Tubod",
                          "Barobo",
                          "Bayabas",
                          "Cagwait",
                          "Cantilan",
                          "Carmen",
                          "Carrascal",
                          "Cortes",
                          "Hinatuan",
                          "Lanuza",
                          "Lianga",
                          "Lingig",
                          "Madrid",
                          "Marihatag",
                          "San Agustin",
                          "San Miguel",
                          "Tagbina",
                          "Tago",
                          "Basilisa",
                          "Cagdianao",
                          "Dinagat",
                          "Libjo",
                          "Loreto",
                          "San Jose",
                          "Tubajon",
                          "Lantawan",
                          "Maluso",
                          "Sumisip",
                          "Tipo-Tipo",
                          "Tuburan",
                          "Akbar",
                          "Al-Barka",
                          "Hadji Mohammad Ajul",
                          "Ungkaya Pukan",
                          "Hadji Muhtamad",
                          "Tabuan-Lasa",
                          "Bacolod-Kalawi",
                          "Balabagan",
                          "Balindong",
                          "Bayang",
                          "Binidayan",
                          "Bubong",
                          "Butig",
                          "Ganassi",
                          "Kapai",
                          "Lumba-Bayabao",
                          "Lumbatan",
                          "Madalum",
                          "Madamba",
                          "Malabang",
                          "Marantao",
                          "Masiu",
                          "Mulondo",
                          "Pagayawan",
                          "Piagapo",
                          "Poona Bayabao",
                          "Pualas",
                          "Ditsaan-Ramain",
                          "Saguiaran",
                          "Tamparan",
                          "Taraka",
                          "Tubaran",
                          "Tugaya",
                          "Wao",
                          "Marogong",
                          "Calanogas",
                          "Buadiposo-Buntong",
                          "Maguing",
                          "Picong",
                          "Lumbayanague",
                          "Amai Manabilang",
                          "Tagoloan Ii",
                          "Kapatagan",
                          "Sultan Dumalondong",
                          "Lumbaca-Unayan",
                          "Ampatuan",
                          "Buldon",
                          "Buluan",
                          "Datu Paglas",
                          "Datu Piang",
                          "Datu Odin Sinsuat",
                          "Shariff Aguak",
                          "Matanog",
                          "Pagalungan",
                          "Parang",
                          "Sultan Kudarat",
                          "Sultan Sa Barongis",
                          "Kabuntalan",
                          "Upi",
                          "Talayan",
                          "South Upi",
                          "Barira",
                          "Gen. s.k. Pendatun",
                          "Mamasapano",
                          "Talitay",
                          "Pagagawan",
                          "Paglat",
                          "Sultan Mastura",
                          "Guindulungan",
                          "Datu Saudi-Ampatuan",
                          "Datu Unsay",
                          "Datu Abdullah Sangki",
                          "Rajah Buayan",
                          "Datu Blah T. Sinsuat",
                          "Datu Anggal Midtimbang",
                          "Mangudadatu",
                          "Pandag",
                          "Northern Kabuntalan",
                          "Datu Hoffer Ampatuan",
                          "Datu Salibo",
                          "Shariff Saydona Mustapha",
                          "Indanan",
                          "Jolo",
                          "Kalingalan Caluang",
                          "Luuk",
                          "Maimbung",
                          "Hadji Panglima Tahil",
                          "Old Panamao",
                          "Pangutaran",
                          "Parang",
                          "Pata",
                          "Patikul",
                          "Siasi",
                          "Talipao",
                          "Tapul",
                          "Tongkil",
                          "Panglima Estino",
                          "Lugus",
                          "Pandami",
                          "Omar",
                          "Panglima Sugala",
                          "Bongao",
                          "Mapun",
                          "Simunul",
                          "Sitangkai",
                          "South Ubian",
                          "Tandubas",
                          "Turtle Islands",
                          "Languyan",
                          "Sapa-Sapa",
                          "Sibutu"
                        ],
                        dropdownSearchDecoration: const InputDecoration(
                          labelText: "Select your Municipality*",
                        ),
                        onChanged: itemSelectionChanged,
                        showSearchBox: true,
                        searchFieldProps: const TextFieldProps(
                          cursorColor: Colors.blue,
                        ),
                      ),
                    ),
//========================================================================
                    const SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: GestureDetector(
                        onTap: signUpUser,
                        child: Container(
                          padding: EdgeInsets.all(20),
                          decoration: BoxDecoration(
                            color: Colors.green[500],
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: const Center(
                            child: Text(
                              'Sign Up',
                              style: TextStyle(
                                color: Colors.white,
                                fontWeight: FontWeight.bold,
                                fontSize: 18,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                    SizedBox(height: 10),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25.0),
                      child: GestureDetector(
                        onTap: () {
                          // Navigator.pop(context);
                          // Navigator.of(context).pushNamed('/home_page');
                          Navigator.of(context).pushNamed(
                            '/',
                            arguments: '',
                          );
                        },
                        child: Container(
                          padding: const EdgeInsets.all(20),
                          decoration: BoxDecoration(
                            color: Colors.blue[800],
                            // color: Colors.grey[500],
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: const Center(
                            child: Text(
                              'Sign In',
                              style: TextStyle(
                                color: Colors.white,
                                fontWeight: FontWeight.bold,
                                fontSize: 18,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
//================================================================================
                    const SizedBox(height: 20),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: const [
                        Text(
                          'I\'m already a Member.',
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),

                    const SizedBox(height: 20),
                  ],
                ),
              ),
            ),
          ),
        ),
      );

  bool isItemDisabled(String s) {
    //return s.startsWith('I');

    if (s.startsWith('I')) {
      return true;
    } else {
      return false;
    }
  }

  void itemSelectionChanged(String? s) {
    // print(s);
  }
}
