// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUAfJqnTPw19SDPcHPpCkqEXmu6vzTllM',
    appId: '1:26197024544:android:fdcb092b8eae50933ac145',
    messagingSenderId: '26197024544',
    projectId: 'schooapp2022',
    databaseURL: 'https://schooapp2022-default-rtdb.firebaseio.com',
    storageBucket: 'schooapp2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwHf9AiPFmzUhQETkp4h6lsCRIP1SlMDU',
    appId: '1:26197024544:ios:d14bba4878d533ea3ac145',
    messagingSenderId: '26197024544',
    projectId: 'schooapp2022',
    databaseURL: 'https://schooapp2022-default-rtdb.firebaseio.com',
    storageBucket: 'schooapp2022.appspot.com',
    androidClientId: '26197024544-2247uv45hchr4l6pe6umpplb26k2t5s2.apps.googleusercontent.com',
    iosClientId: '26197024544-lr3dkiknmppb2qejctchkls8l572qtb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.alerto24',
  );
}
